### ISSUE TITLE
Why do you spread malware and viruses? UPX is virus!

### ISSUE THREAD

**Issue by PELock** [upx/upx#445] opened 2020-12-30 13:03 UTC
I have packed notepad.exe (renamed to test.exe) using the latest version of UPX 3.96.

https://www.virustotal.com/gui/file/e67d349e4bcf768c5d490216c8fae79a8f022d49d6b10a35fbfb89be129a659a/detection

Virustotal says it's a virus! 10/71 said UPX is a virus!

Antiy-AVL

GrayWare/Win32.Generic
Bkav

W32.AIDetectVM.malware2
Comodo

TrojWare.Win32.Dialer.d36@48x949
Cylance

Unsafe
Cynet

Malicious (score: 100)
FireEye

Generic.mg.d1a8d14f037b6dcf
Qihoo-360

HEUR/QVM11.1.45C2.Malware.Gen
VBA32

TrojanPSW.QQpass
Webroot

W32.Trojan.Ghgm
Yandex

Trojan.GenAsa!ySp/bQyWY/k

Why do you spread malware and viruses?!

**Comment by bitraid** [comment] 2020-12-30 14:34
Is this a joke?

**Comment by PELock** [comment] 2020-12-30 16:25
No, look at the VirusTotal report.

**Comment by PELock** [comment] 2020-12-30 16:26
Look at:

https://www.virustotal.com/gui/file/e67d349e4bcf768c5d490216c8fae79a8f022d49d6b10a35fbfb89be129a659a/details

PEiD packer	UPX v0.89.6 - v1.02 / v1.05 -v1.24 -> Markus & Laszlo [overlay]

UPX is a virus/malware! Why do you spread malware?

**Comment by bitraid** [comment] 2020-12-30 16:49
First answer me these questions:
1. Why do YOU spread malware? PELock is a virus/malware! Look at:  https://www.virustotal.com/gui/file/66b8822649e92ecb9b5003d7b34064e1f95a4a06997914c1f1e4e84aae3258f0/detection
2. Where is the "virus" in this code, which just calls `ExitProcess` and flagged by VirusTotal:
https://www.virustotal.com/gui/file/a0c005047e97f2acb0368d4fa9838f3eef1ce60fc1f1d46f4992bb4a72ecc84d/detection
```asm
format PE GUI
entry start

section '.text' code readable executable

  start:
    call    [ExitProcess]

section '.idata' import data readable writeable

  dd 0,0,0,RVA kernel_name,RVA kernel_table
  dd 0,0,0,0,0

  kernel_table:
    ExitProcess dd RVA _ExitProcess
    dd 0

  kernel_name db 'KERNEL32.DLL',0

  _ExitProcess dw 0
    db 'ExitProcess',0
```
3. Do you know what a "false positive" is?
4. Do you know that many AV programs flag files not just by code but from the binary hash and timestamps?

**Comment by PELock** [comment] 2020-12-30 23:36
UPX is malware! There's no doubt in it. 10 antivirus engines in respected VirusTotal fully support that claim!

Why Markus won't do anything about it???

**Comment by bitraid** [comment] 2020-12-31 08:10
There is this pinned issue #437, but you must have the brains to understand that these are false positives.

**Comment by PELock** [comment] 2020-12-31 11:50
So why don't you do anything with it? Isn't malware bad for users? Why do you allow malware in UPX?

**Comment by markus-oberhumer** [comment] 2021-01-06 16:24
Duplicate of #437.

Note hat PELock (Bartosz Wójcik) is the author of various **commerical** executable "protection" and compression utilities (see  https://www.pelock.com) which might be regarded as a direct competition to UPX. Still - even more when considering his long term background in the scene - I personally find his comments here extremely unprofessional.

Don't feed the trolls.

**Closed by markus-oberhumer** 2021-01-06 16:24 UTC

**Comment by PELock** [comment] 2021-01-06 17:27
It's nice of you to reply to me for the first time in 14 years. All it took was a little trolling :)
