### ISSUE TITLE
Error CantPackException

### ISSUE THREAD

**Issue by alitalibiq** [upx/upx#217] opened 2018-08-30 15:10 UTC
How are you, brother
When I work on Upx it beats me wrong
I am executing such a video
[https://www.youtube.com/watch?v=3v8rJJCWVRk](url)
Himself, I do not have the same fault as in this picture
[https://e.top4top.net/p_9723loa81.png](url)

---The codes that I use even get this error in cmd--
* cd desktop
* upx
* upx.exe -9 -o packed.exe "fa.exe"

Error: upx: fa.exe: CantPackException: .NET files are not yet supported

---Requirements used---
* UPX 3.95w 
* Windows10  32bit

**Comment by markus-oberhumer** [comment] 2018-09-02 18:14
Duplicate of #37 .

**Closed by markus-oberhumer** 2018-09-02 18:14 UTC

**Comment by HACLANG** [comment] 2018-10-11 13:18
Hello.@alitalibiq 

The following content is quoted from the author Phill Tew and may be helpful.

[https://superuser.com/questions/114500/upx-and-net-executables/1365888#1365888](Look here)

`UPX is only for native executables. There are a number of compressors for .NET executables around you could try my one RPX it does good compression even on small executables and can bundle multiple DLL(s) into a single .EXE file.

However there are some limitations caused by the manner, or more precisely the order, by which .NET looks for additional assemblies to load and where from (i.e 1. GAC, 2. File system, 3. Bundle) and is complicated more if you are using AppDomains inside your application.

Check the docs for more details. Hope that helps.`
