### ISSUE TITLE
4.0.2 and later versions cannot support darwin-arm64 golang program compression

### ISSUE THREAD

**Issue by IzanamI1999** [upx/upx#748] opened 2023-12-20 13:22 UTC
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* Host Operating System and version:
* Host CPU architecture:
* Target Operating System and version:
* Target CPU architecture:

**Comment by jreiser** [comment] 2023-12-20 14:11
You must supply an actual test case example that fails.  Give a URL, or see "Paste, drop, or click to add files" in the footer of any pane to enter a Comment here on github.

**Comment by IzanamI1999** [comment] 2023-12-21 01:16
Need to use -- force-macos. Does this have any effect?

**Comment by markus-oberhumer** [comment] 2024-02-12 14:43
Unfortunately UPX compressed binaries currently do not work on macOS 13 or later, thanks to undocumented changes by Apple.

Closing as duplicate of https://github.com/upx/upx/issues/612

**Closed as not planned by markus-oberhumer** 2024-02-12 14:43 UTC
Labels: duplicate, os:macOS
