### ISSUE TITLE
Upx compressed mipsel program cannot run in the Linux environment of mipsel

### ISSUE THREAD

**Issue by llfj** [upx/upx#350] opened 2020-03-05 14:12 UTC
## What's the problem (or question)?

Upx compressed mipsel program cannot run in the Linux environment of mipsel

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):   
UPX 3.96w
* Host Operating System and version:
cetnos7 and  windows10
* Host CPU architecture:
x68_64
* Target Operating System and version:
linux_openwrt  linux_padavan
* Target CPU architecture:
mipsel (MT7621a and MT7620)

**Comment by jreiser** [comment] 2020-03-05 21:26
Please upload ("Attach files by ...") an actual executable that fails to run.  Compress the upload using zip, gzip, or .tgz in order to save space on Github.
Please run the compressed-by-UPX executable under `strace`, then copy+paste the output into a Comment here.  Place a line that contains three backtick characters (decimal 96, hex 0x60, octal 0140; often on a key to the left of the `1` key) both before and after the strace output, so that the formatting by Github uses constant-width characters on a lightly-shaded background.
Please post the URLs for downloadable images of "inux_openwrt linux_padavan" so that the environment can be reproduced.

**Comment by elitah** [comment] 2020-03-08 09:09
I have the same problem, but it works in the old version(UPX 3.95w)

In the new version(UPX 3.96w), it looks like a dead cycle, with 95% CPU utilization

It's an embedded openwrt in mipsle

**Comment by jreiser** [comment] 2020-03-08 13:55
@elitah What is the manufacturer, model, hardware version, and serial number of your device?  You may substitute `X` for the low-order 4 digits of the serial number, such as `345XXXX`.

**Comment by llfj** [comment] 2020-03-09 01:45
[n2n_v2_linux_mipsel_v2.5.1_r247_static_by_heiye.tar.gz](https://github.com/upx/upx/files/4304225/n2n_v2_linux_mipsel_v2.5.1_r247_static_by_heiye.tar.gz)

``[root@mshome_DF:/tmp]#strace ./edge_upx
``execve("./edge_upx", ["./edge_upx"], 0x7ffbd970 /* 13 vars */) = 0
``open("/proc/self/exe", O_RDONLY)        = 3
``mmap(NULL, 75792, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x77b3d000
``mmap(0x77b3d000, 74945, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED, 3, 0) = ``0x77b3d000
``cacheflush(0x77b4edd8, 0xa38, 0x3)      = 0
``mprotect(0x77b4e000, 6160, PROT_READ|PROT_EXEC) = 0
``readlink("/proc/self/exe", "/tmp/edge_upx", 4095) = 13
``cacheflush(0x7fd681a0, 0x134, 0x3)      = 0
``mmap(0x400000, 253952, PROT_NONE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x400000
``mmap(0x400000, 179796, PROT_READ|PROT_WRITE, ``MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x400000
``cacheflush(0x400000, 0x134, 0x3)        = 0
``cacheflush(0x400134, 0x2bd20, 0x3)      = 0
``mprotect(0x400000, 179796, PROT_READ|PROT_EXEC) = 0
``
URLs for downloadable images:
https://downloads.openwrt.org/releases/19.07.0/targets/ramips/

**Comment by jreiser** [comment] 2020-03-09 02:42
It looks like this problem is the same as https://github.com/upx/upx/issues/342 and https://github.com/upx/upx/issues/339 which was fixed by commit 4fb1d41be8acd16849fab9622f35903d3fc4a7d9 on the `devel` branch.  Please try the tip of `devel` branch which currently is b72eac69a5de09e63c77838f4cd22be1de54805f.  A build for Windows64 can located starting at https://github.com/upx/upx-automatic-builds/tree/devel-20200215-b72eac6-appveyor.

**Comment by llfj** [comment] 2020-03-09 03:02
It can run with upx-git-b72eac69a5de.exe  compression

**Closed** 2020-03-16 00:12 UTC
