### ISSUE TITLE
CantPackException: bad DT_GNU_HASH n_bucket=0x1  n_bitmask=0x1  len=0x20  r=6

### ISSUE THREAD

**Issue by Zopolis4** [upx/upx#834] opened 2024-06-28 02:41 UTC
## What's the problem (or question)?
upx fails to compress several of my mysql binaries, throwing an identical error each time.
```
chronos@915f619055db ~/u/l/bin [1]> upx --lzma mysqltest_safe_process
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2024
UPX 4.2.3       Markus Oberhumer, Laszlo Molnar & John Reiser   Mar 27th 2024

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: mysqltest_safe_process: CantPackException: bad DT_GNU_HASH n_bucket=0x1  n_bitmask=0x1  len=0x20  r=6

Packed 0 files.
```

## What should have happened?
The executable should have compressed successfully.

## Do you have an idea for a solution?
No.

## How can we reproduce the issue?
1. `sudo docker run --platform linux/amd64 --rm -it satmandu/crewbuild:amd64`
Once inside the container:
2. `crew update`
3. `cd`
4. `git clone https://github.com/chromebrew/chromebrew`
5. `cd chromebrew`
6. `crew build -kf mysql`
7. The resulting binaries will be present in a `.tar.zst` file in the `release/x86_64` directory, in the `usr/bin` path within the file.

For convenience, I have also attached a failing executable here, compressed to `.tar.gz` so that github will allow the upload.
[mysqltest_safe_process.tar.gz](https://github.com/user-attachments/files/16023489/mysqltest_safe_process.tar.gz)

## Please tell us details about your environment.

* UPX version used (`upx --version`): `upx 4.2.3 UCL data compression library 1.03 zlib data compression library 1.3.1.1-motley LZMA SDK version 4.43 doctest C++ testing framework version 2.4.11`
* Host Operating System and version: `ChromeOS`, `Milestone 125`
* Host CPU architecture: `x86_64`
* Target Operating System and version: `ChromeOS`, `Milestone 125`
* Target CPU architecture: `x86_64`

**Comment by jreiser** [comment] 2024-06-28 03:30
So far, this looks like another case of https://github.com/rust-lang/rust/issues/100859  , "Undocumented use of DT_GNU_HASH descriptor", from 2022-08-21, not quite 2 years ago.
Edit: this time symbias is 0x24, but the one symbol has an index of 0, which is not at least 0x24.

**Comment by Zopolis4** [comment] 2024-06-28 03:34
MySQL isn't written in rust, unless I'm misunderstanding things?

**Comment by jreiser** [comment] 2024-06-29 03:09
Fixed by commit 64a3de5a7a1b44772c8da47b0c77f134380b0cd1 .
Builds are available on the Actions page https://github.com/upx/upx/actions/runs/9719671780 .

**Comment by markus-oberhumer** [comment] 2024-07-02 04:06
@jreiser Your fix has caused regressions on i386, reopening.

https://github.com/upx/upx-workflows-github-actions/actions/runs/9753857402

https://github.com/upx/upx-workflows-github-actions/actions/runs/9753972367

**Comment by jreiser** [comment] 2024-07-02 15:04
> @jreiser Your fix has caused regressions on i386, reopening.
> 
> https://github.com/upx/upx-workflows-github-actions/actions/runs/9753857402
> 
> https://github.com/upx/upx-workflows-github-actions/actions/runs/9753972367

@markus-oberhumer   Please supply an actual upx executable file which fails.

When I do a fresh clone of the devel branch, then it works for me:
```
$ git checkout devel
$ git log
commit 64a3de5a7a1b44772c8da47b0c77f134380b0cd1 (HEAD -> devel, origin/devel, origin/HEAD)
Author: John Reiser <jreiser@BitWagon.com>
Date:   Fri Jun 28 08:54:30 2024 -0700

    FIX PT_GNU_HASH when "empty"
    
    ... such as a main program with no exported globals
    https://github.com/upx/upx/issues/834
            modified:   p_lx_elf.cpp

commit 261609f706c0d57080eccd040606ada2dd83df08
Author: Markus F.X.J. Oberhumer <markus@oberhumer.com>
Date:   Wed Jun 26 11:45:35 2024 +0200

    CI updates

   [[snip]]
```
and then build and test it locally using Fedora 38:
```
$ rm -rf ./build/extra/gcc-m32
$ make     build/extra/gcc-m32/all+test
   [[snip]]
cd "build/extra/gcc-m32/release" && ctest --output-on-failure --parallel 8 -C Release
Test project /Sam2T/home/jreiser/upx-test/upx/build/extra/gcc-m32/release
        Start  10: upx-self-pack
        Start 234: upx-self-pack-lzma-7
        Start 227: upx-self-pack-lzma-6
        Start 220: upx-self-pack-lzma-5
        Start 213: upx-self-pack-lzma-4
        Start 206: upx-self-pack-lzma-3
        Start 199: upx-self-pack-lzma-2
        Start 192: upx-self-pack-lzma-1
  1/240 Test  #10: upx-self-pack ....................   Passed    0.18 sec
   [[snip]]
234/240 Test #219: upx-run-packed-lzma-4 ............   Passed    0.06 sec
235/240 Test #223: upx-test-lzma-5 ..................   Passed    0.05 sec
236/240 Test #226: upx-run-packed-lzma-5 ............   Passed    0.05 sec
237/240 Test #230: upx-test-lzma-6 ..................   Passed    0.05 sec
238/240 Test #237: upx-test-lzma-7 ..................   Passed    0.05 sec
239/240 Test #233: upx-run-packed-lzma-6 ............   Passed    0.06 sec
240/240 Test #240: upx-run-packed-lzma-7 ............   Passed    0.06 sec

100% tests passed, 0 tests failed out of 240

Total Test time (real) =   2.25 sec
$ 
```

On the first Actions page 9753857402 I see in the left nav Jobs column: 11 success for x86_64, followed by 11 failure for i386.

On the second Actions page 9753972367 I see in the left nav Jobs column: 11 success for x86_64, followed by  4 failures for i386 alpine 3.9, 3.10, 3.11, 3.12, then 9 success for i386 alpine 3.13 through 3.20 and edge.  It seems to me that the build+test harness does not control the version of the static binder /usr/bin/ld and dynamic linker /lib/ld-linux.so.2, which are the producer and consumer of the GNU_HASH table.

In order to debug I must have an actual executable which fails, and a "corresponding" executable which succeeds.  Neither of the Acitons pages produces any downloadable Artifacts.  My re-build and test succeeds locally on Fedora 38.

(Edit: My version of /usr/bin/ld is GNU ld version 2.39-16.fc38.
My version of /lib/ld-linux.so.2 is ld.so (GNU libc) stable release version 2.37. )

**Comment by markus-oberhumer** [comment] 2024-07-02 15:42
@jreiser You obviously only do minimal testing - don't you have a private testsuite collection with hundreds of files to check for regressions???

Anyway, there is https://github.com/upx/upx-testsuite-v2

and especially all files from

https://github.com/upx/upx-testsuite-v2/tree/master/files/all/i386-linux.elf

**Comment by jreiser** [comment] 2024-07-02 15:47
@markus-oberhumer  The person who alleges a bug must provide an actual specific reproducible example which fails.

**Comment by markus-oberhumer** [comment] 2024-07-02 15:55
@jreiser No, the person who adds a commit must make sure to not introduce regression by **thorough** testing.

I request that you test all files from https://github.com/upx/upx-testsuite-v2/tree/master/files/all for regressions against upx-4.2.4, including packing, listing, correct unpacking and actually executing.

**Comment by jreiser** [comment] 2024-07-05 18:05
Commit 64a3de5a7a1b44772c8da47b0c77f134380b0cd1 (FIX PT_GNU_HASH when "empty") is an enhancement that detects PT_GNU_HASH with malformed contents in more cases than previously. The commit fixes the bug shown in the Description of this Issue. An input file with a well-formed PT_GNU_HASH does not draw a complaint from this Commit.

Some versions of static binders (`/usr/bin/ld`, golang ld, Rust, lld) produce malformed PT_GNU_HASH, especially for `-static` builds. As a result, Commit 64a3de5 complains.  In upx-testsuite-v2 then `upx -l` with 64a3de5 shows 80 complaints, summarized by:
```
#    number  directory     example with malformed PT_GNU_HASH
     16/97   files/all/armeb-linux.elf/  upx_test01_sf_a_exe_static_pie_c.out
     32/193  files/all/arm-linux.elf/    upx_test01_sf_a_exe_static_pie_c.out
     16/97   files/all/i386-linux.elf/   upx_test01_i586_exe_static_pie_c.out
     16/97   files/all/powerpc-linux.elf/  upx_test01_hf_exe_static_pie_c.out
     ======================
     80/1153  files/all/...
```
Because malformed PT_GNU_HASH is common, then Commit 9271bbcb3fc8bd4ec6cf62be09dcf16c34ad65b8 on branch `jreiser-GNU_HASH` works around it, and there are no complaints from running `upx -l` on upx-testsuite-v2.  The CI Actions page for checkin https://github.com/upx/upx/actions/runs/9810658827/job/27091290558 succeeds. @markus-oberhumer  please incorprate Commit 9271bbc into the `devel` branch.

Executive summary:
The root cause of most of the trobule is how to represent an "empty" PT_GNU_HASH; that is, one with no successful lookups, such as a `-static` build which does not export any symbols.  Apparently the obvious solution of  "omit PT_GNU_HASH entirely" is not adopted.  This seems a pity becuase it would merely add a guarding `if (!ptr_PT_GNU_HASH)` in front of the calls to lookup(), which might force the use of the fall-back methods of using PT_HASH (if present) or sequential scan of DT_DYNSYM.

Why does `upx -l` complain but `readelf` does not?  Because `readelf` does not care about symbol table lookups.  But upx must lookup `JNI_OnLoad` because that symbol is an initializer which must be integrated with DT_INIT and DT_INITARRAY.  Java uses this because it wants to be independent of OS and non-Java runtime libraries.

Details:  In glibc, the relevant code is:
```
# elf/dl-setup_hash.c:
      Elf32_Word *hash32
        = (void *) D_PTR (map, l_info[ELF_MACHINE_GNU_HASH_ADDRIDX]);
      map->l_nbuckets = *hash32++;
      Elf32_Word symbias = *hash32++;
      Elf32_Word bitmask_nwords = *hash32++;
      /* Must be a power of two.  */
      assert ((bitmask_nwords & (bitmask_nwords - 1)) == 0);
      map->l_gnu_bitmask_idxbits = bitmask_nwords - 1;
      map->l_gnu_shift = *hash32++;

      map->l_gnu_bitmask = (ElfW(Addr) *) hash32;
      hash32 += __ELF_NATIVE_CLASS / 32 * bitmask_nwords;

      map->l_gnu_buckets = hash32;
      hash32 += map->l_nbuckets;
      map->l_gnu_chain_zero = hash32 - symbias;

# elf/dl-lookup-direct.c:
      Elf32_Word bucket = map->l_gnu_buckets[new_hash % map->l_nbuckets];
        /* snip */
           const Elf32_Word *hasharr = &map->l_gnu_chain_zero[bucket];
```
In the simplest interpretation, then the `symbias` element is used to save space in the hashtable by omitting the leading portion which would be all-zero because none of the actual symbols in DT_DYNSYM hash to those indices.

So, how should an "empty", but never-the-less present, PT_GNU_HASH be represented?  The actual values used by the Description of this current Issue #834, are `n_buckets = 1`, `symbias=36`, `bitmask_nwords = 1`, `shift = 26`, `bitmask[0] = 0ul`, `bucket[0] = 0`.  Because `1 == n_buckets` then the remainder operation gives a hashtable index of 0; and `0 == hasharr[0]`. Thus there are no pairs of `1` bits in the hash table, so no pairs of bits which AND to `1`, and lookup() should fail. A static binder for such an "empty" PT_GNU_HASH might be tempted to reduce space by omitting `buckets[0]` because it believes that `new_hash < symbias` precludes any successful search; but this conflicts with `n_buckets = 1`.  Another temptation is to omit `bitmask[0]`, but this conflicts with `bitmask_nwords = 1`. Succumbing to either of these temptations results in a PT_GNU_HASH with total size less than indicated by the header values, which is malformed.  Yet another temptation is to truncate the table of hash bits on the high end of the set of actual hash remainders, much like `symbias` on the low end.  Some versions of Rust do this, which is another malformed case (which is detected and overlooked).
In general, a "successful" lookup gives an index into the DYNSYM table, and the index must be checked against its length.

One indication of the variance of PT_GNU_HASH implementations is shown by https://github.com/upx/upx-workflows-github-actions/actions/runs/9753972367 where i386 fails for alpine-3.9 through -3.12, but succeeds with alpine-3.13 through -3.20 and -edge.  Therefore it is useful to know which static binder was used.  @markus-oberhumer , please enhance the CI scripts to show the `--version` of `/usr/bin/ld` or other static binder. Similarly, please document the versions used for each directory of upx-testsuite-v2.

**Comment by markus-oberhumer** [comment] 2024-07-06 10:04
@jreiser You can see the binutils versions by expanding the `Install packages i386/alpine:X.YY` section of the CI log.

Also note that this seems not restricted to 3.9..3.12, when using `gcc -static-pie` **all** i386 versions fail:

https://github.com/upx/upx-workflows-github-actions/actions/runs/9753995665

**Comment by markus-oberhumer** [comment] 2024-07-06 13:09
@jreiser upx-testsuite-v2 is documented here

https://github.com/upx/upx-testsuite-v2/blob/master/misc/create-files/build.sh

You should be able to build byte-identical results if you install /usr/local/bin/upx-linux-musl-gcc-9.2.0-toolchains-20200226

**Closed as completed** 2024-07-10 09:16 UTC
Labels: os:Linux
