### ISSUE TITLE
upx devel branch can not compress mips32 .so file

### ISSUE THREAD

**Issue by Koi-YC** [upx/upx#473] opened 2021-03-22 02:01 UTC
## What's the problem (or question)?

./upx.out navie.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-4893d9+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: navie.so: CantPackException: bad DT_HASH nbucket=0x407  len=0x2eac

Packed 0 files.

## What should have happened?

I can  compress executable file successfully，but fail to compress .so file.
some detail of navie.so is as below.
readelf -h navie.so
ELF Header:
  Magic:   7f 45 4c 46 01 02 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, big endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           MIPS R3000
  Version:                           0x1
  Entry point address:               0x1af60
  Start of program headers:          52 (bytes into file)
  Start of section headers:          1250892 (bytes into file)
  Flags:                             0x50001007, noreorder, pic, cpic, o32, mips32
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         6
  Size of section headers:           40 (bytes)
  Number of section headers:         30
  Section header string table index: 29

## How can we reproduce the issue?

1.
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):
* upx 4.0.0-git-4893d995f298+
UCL data compression library 1.03
zlib data compression library 1.2.8
LZMA SDK version 4.43

* Host Operating System and version:
Linux tplink 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Host CPU architecture:
cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
stepping        : 9
microcode       : 0x42
cpu MHz         : 3400.000
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti retpoline intel_pt rsb_ctxsw tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 6816.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
stepping        : 9
microcode       : 0x42
cpu MHz         : 3400.000
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 1
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti retpoline intel_pt rsb_ctxsw tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 6816.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
stepping        : 9
microcode       : 0x42
cpu MHz         : 3400.000
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 2
cpu cores       : 4
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti retpoline intel_pt rsb_ctxsw tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 6816.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
stepping        : 9
microcode       : 0x42
cpu MHz         : 3400.000
cache size      : 6144 KB
physical id     : 0
siblings        : 4
core id         : 3
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti retpoline intel_pt rsb_ctxsw tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 6816.00
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

* Target Operating System and version:
Linux version 3.4.11-rt19 (root@tplink) (gcc version 4.6.2 (Buildroot 2011.11) ) #18 SMP PREEMPT Tue Mar 9 14:10:54 CST 2021
* Target CPU architecture:
system type             : 963168XF
processor               : 0
cpu model               : Broadcom BMIPS4350 V8.0
BogoMIPS                : 397.31
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : no
hardware watchpoint     : no
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

processor               : 1
cpu model               : Broadcom BMIPS4350 V8.0
BogoMIPS                : 403.45
wait instruction        : yes
microsecond timers      : yes
tlb_entries             : 32
extra interrupt vector  : no
hardware watchpoint     : no
ASEs implemented        :
shadow register sets    : 1
kscratch registers      : 0
core                    : 0
VCED exceptions         : not available
VCEI exceptions         : not available

**Comment by jreiser** [comment] 2021-03-22 02:51
Please run `readelf --headers --segments --dynamic navie.so` then copy+paste the results here.  Or, provide the URL to an actual file which fails.

**Comment by Koi-YC** [comment] 2021-03-22 05:52
readelf --headers --segments --dynamic navie.so
ELF Header:
  Magic:   7f 45 4c 46 01 02 01 00 00 00 00 00 00 00 00 00
  Class:                             ELF32
  Data:                              2's complement, big endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           MIPS R3000
  Version:                           0x1
  Entry point address:               0x1af60
  Start of program headers:          52 (bytes into file)
  Start of section headers:          1250892 (bytes into file)
  Flags:                             0x50001007, noreorder, pic, cpic, o32, mips32
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         6
  Size of section headers:           40 (bytes)
  Number of section headers:         30
  Section header string table index: 29

Section Headers:
  [Nr] Name              Type            Addr     Off    Size   ES Flg Lk Inf Al
  [ 0]                   NULL            00000000 000000 000000 00      0   0  0
  [ 1] .reginfo          MIPS_REGINFO    000000f4 0000f4 000018 18   A  0   0  4
  [ 2] .dynamic          DYNAMIC         0000010c 00010c 0000f0 08   A  5   0  4
  [ 3] .hash             HASH            000001fc 0001fc 002eac 04   A  4   0  4
  [ 4] .dynsym           DYNSYM          000030a8 0030a8 007a20 10   A  5   2  4
  [ 5] .dynstr           STRTAB          0000aac8 00aac8 00a1f5 00   A  0   0  1
  [ 6] .gnu.version      VERSYM          00014cbe 014cbe 000f44 02   A  4   0  2
  [ 7] .gnu.version_r    VERNEED         00015c04 015c04 000020 00   A  5   1  4
  [ 8] .rel.dyn          REL             00015c24 015c24 0052b0 08   A  4   0  4
  [ 9] .init             PROGBITS        0001aee4 01aee4 000078 00  AX  0   0  4
  [10] .text             PROGBITS        0001af60 01af60 0c9780 00  AX  0   0 16
  [11] .MIPS.stubs       PROGBITS        000e46e0 0e46e0 000ea0 00  AX  0   0  4
  [12] .fini             PROGBITS        000e5580 0e5580 000050 00  AX  0   0  4
  [13] .rodata           PROGBITS        000e55d0 0e55d0 035ba0 00   A  0   0 16
  [14] .eh_frame_hdr     PROGBITS        0011b170 11b170 00001c 00   A  0   0  4
  [15] .eh_frame         PROGBITS        0011b18c 11b18c 000040 00   A  0   0  4
  [16] .ctors            PROGBITS        0012b1cc 11b1cc 000008 00  WA  0   0  4
  [17] .dtors            PROGBITS        0012b1d4 11b1d4 000008 00  WA  0   0  4
  [18] .jcr              PROGBITS        0012b1dc 11b1dc 000004 00  WA  0   0  4
  [19] .data.rel.ro      PROGBITS        0012b1e0 11b1e0 0011f8 00  WA  0   0  4
  [20] .data             PROGBITS        0012c3e0 11c3e0 003490 00  WA  0   0 16
  [21] .got              PROGBITS        0012f870 11f870 001cf4 04 WAp  0   0 16
  [22] .sdata            PROGBITS        00131564 121564 000004 00 WAp  0   0  4
  [23] .sbss             PROGBITS        00131568 121568 000024 00 WAp  0   0  4
  [24] .bss              NOBITS          00131590 12158c 0174b8 00  WA  0   0 16
  [25] .pdr              PROGBITS        00000000 12158c 00ff80 00      0   0  4
  [26] .comment          PROGBITS        00000000 13150c 000030 01  MS  0   0  1
  [27] .gnu.attributes   LOOS+ffffff5    00000000 13153c 000010 00      0   0  1
  [28] .mdebug.abi32     PROGBITS        00148a48 13154c 000000 00      0   0  1
  [29] .shstrtab         STRTAB          00000000 13154c 0000ff 00      0   0  1
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings)
  I (info), L (link order), G (group), T (TLS), E (exclude), x (unknown)
  O (extra OS processing required) o (OS specific), p (processor specific)

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  REGINFO        0x0000f4 0x000000f4 0x000000f4 0x00018 0x00018 R   0x4
  LOAD           0x000000 0x00000000 0x00000000 0x11b1cc 0x11b1cc R E 0x10000
  LOAD           0x11b1cc 0x0012b1cc 0x0012b1cc 0x063c0 0x1d87c RW  0x10000
  DYNAMIC        0x00010c 0x0000010c 0x0000010c 0x000f0 0x000f0 RWE 0x4
  GNU_EH_FRAME   0x11b170 0x0011b170 0x0011b170 0x0001c 0x0001c R   0x4
  NULL           0x000000 0x00000000 0x00000000 0x00000 0x00000     0x4

 Section to Segment mapping:
  Segment Sections...
   00     .reginfo
   01     .reginfo .dynamic .hash .dynsym .dynstr .gnu.version .gnu.version_r .rel.dyn .init .text .MIPS.stubs .fini .rodata .eh_frame_hdr .eh_frame
   02     .ctors .dtors .jcr .data.rel.ro .data .got .sdata .sbss .bss
   03     .dynamic
   04     .eh_frame_hdr
   05

Dynamic section at offset 0x10c contains 24 entries:
  Tag        Type                         Name/Value
 0x00000001 (NEEDED)                     Shared library: [libgcc_s.so.1]
 0x00000001 (NEEDED)                     Shared library: [libc.so.0]
 0x0000000c (INIT)                       0x1aee4
 0x0000000d (FINI)                       0xe5580
 0x00000004 (HASH)                       0x1fc
 0x00000005 (STRTAB)                     0xaac8
 0x00000006 (SYMTAB)                     0x30a8
 0x0000000a (STRSZ)                      41461 (bytes)
 0x0000000b (SYMENT)                     16 (bytes)
 0x00000003 (PLTGOT)                     0x12f870
 0x00000011 (REL)                        0x15c24
 0x00000012 (RELSZ)                      21168 (bytes)
 0x00000013 (RELENT)                     8 (bytes)
 0x70000001 (MIPS_RLD_VERSION)           1
 0x70000005 (MIPS_FLAGS)                 NOTPOT
 0x70000006 (MIPS_BASE_ADDRESS)          0x0
 0x7000000a (MIPS_LOCAL_GOTNO)           51
 0x70000011 (MIPS_SYMTABNO)              1954
 0x70000012 (MIPS_UNREFEXTNO)            37
 0x70000013 (MIPS_GOTSYM)                0x98
 0x6ffffffe (VERNEED)                    0x15c04
 0x6fffffff (VERNEEDNUM)                 1
 0x6ffffff0 (VERSYM)                     0x14cbe
 0x00000000 (NULL)                       0x0

**Comment by jreiser** [comment] 2021-03-23 02:02
Thank you for running and posting the output from `readelf`.  Now I need to see the contents of the DT_HASH region which begins at offset 0x1fc and ends at offset 0x30a8.  One way to do this is:
```
dd if=navie.so of=foo bs=16 count=779
gzip foo
```
then upload ("Attach files by ...") foo.gz which will be at most 12kB.  (Plain `zip` compression also is accepted by github.) Or, send me an email with foo.gz attached.  Or, post a link to the whole navie.so file.

**Comment by jreiser** [comment] 2021-03-23 13:55
Thank you for sending the DT_HASH info.  The above commit should fix the problem.

**Comment by Koi-YC** [comment] 2021-03-24 08:26
Thanks, I can compress the navie.so using newest code now. 
However, there are two more problems.
1. There was a segment fault in the program calling  compressed library. 
2. I tried to compress other .so file and it is fail as below:
./upx.out a.so
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2021
UPX git-be68e8+ Markus Oberhumer, Laszlo Molnar & John Reiser    Jan 1st 2021

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx.out: a.so: CantPackException: DT_NULL not found

Packed 0 files.

**Comment by jreiser** [comment] 2021-03-24 12:53
SIGSEGV: please run under `strace`, then post the last 20 lines.  Also run under a debugger such as gdb (or gdbserver) and show:
```
(gdb) info proc   # get process ID
(gdb) shell cat /proc/PID/maps   # PID is process ID found by line above
(gdb) x/11i $pc-5*4   # instruction stream surrounding point of fault
(gdb) info reg   # all general registers
```
CantPack: As in original case, I need to examine the DT_HASH (and/or DT_GNU_HASH) region.  Probably it runs from (HASH) to (SYMTAB) as shown by `readelf --dynamic`.  Adjust the parameters to `dd` accordingly.

**Comment by Koi-YC** [comment] 2021-03-25 01:31
SIGSEGV: OK, I will try.
CantPack: I have sent mail to you yesterday, please check.

**Comment by jreiser** [comment] 2021-03-26 01:48
CantPack: found the mail; the commit above should fix it.  For auto-build see #476.

**Comment by Koi-YC** [comment] 2021-03-30 09:28
The gdb in cross toolchain do not support "info proc", so I can not get informations of maps. I have sent you other informations by email.

**Comment by Koi-YC** [comment] 2021-04-06 00:40
any update？

**Comment by jreiser** [comment] 2021-04-06 20:17
I have procured this device:
```
/etc/motd:
 OpenWrt 18.06.1, r7258-5eb055306f

uname -a:
Linux GL-AR300M 4.9.120 #0 Thu Aug 16 07:51:15 2018 mips GNU/Linux

cat /proc/cpuinfo:
system type		: Qualcomm Atheros QCA9533 ver 2 rev 0
machine			: GL.iNet GL-AR300M
processor		: 0
cpu model		: MIPS 24Kc V7.4
BogoMIPS		: 432.53
hardware watchpoint	: yes, count: 4, address/irw mask: [0x0ffc, 0x0ffc, 0x0f
fb, 0x0ffb]
isa			: mips1 mips2 mips32r1 mips32r2

ldd /bin/date:
	/lib/ld-musl-mips-sf.so.1 (0x777e2000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x777be000)
	libc.so => /lib/ld-musl-mips-sf.so.1 (0x777e2000)
```
I am trying to build `gdb` and/or `gdbserver` to run on it.  The OpenWRT buid environment which uses amd64 host to build for target mips, uses  libmusl for the C runtime library on the target, and is tedious to build.  The Debian cross-build environment which uses amd64 host to build for target mips, looks easier to bring up, but uses glibc for the C runtime library on the target, which complicates running on the target device because of the difference between libc and libmusl.
If a gdb and/or gdbserver package could be supplied for the mips target device, then progress could be made sooner.

**Comment by Koi-YC** [comment] 2021-04-08 08:19
Sorry, I don't have gdb and/or gdbserver package could be supplied for the mips target device. But I can try to prepare an environment for you to debug it  from remote. I will inform you if it is ok.

**Comment by Koi-YC** [comment] 2021-04-13 09:22
The network is not stable, so it is hard to do remote control. 
I have tried another .so file(program:pktCap), and there is the same problem. However, I get all information you want this time. 
I use gdbserver, the results are as below:
1. partial result of cmd "ps":
 2213 admin     1244 S    ./gdbserver 192.168.1.102:1111 pktCap
 2216 admin      200 t    pktCap
 2218 admin     1520 S    -sh
20437 admin     1512 R    ps

2 partial result of cmd ./ldd /usr/bin/pktCap
ldd: can't open cache '/etc/ld.so.cache'
        libcutil.so => /lib/libcutil.so (0x771f3000)
        ........
        libpcap.so.1 => /lib/libpcap.so.1 (0x76f2a000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x76ef0000)
        libc.so.0 => /lib/libc.so.0 (0x76e71000)
        ld-uClibc.so.0 => /lib/ld-uClibc.so.0 (0x77210000)

3. result of cmd "cat /proc/2216/maps"
00400000-00407000 r-xp 00000000 1f:00 417        /usr/bin/pktCap
00416000-00417000 rw-p 00006000 1f:00 417        /usr/bin/pktCap
771a8000-771ad000 r-xp 00000000 1f:00 200        /lib/ld-uClibc-0.9.32.so
771bc000-771be000 rw-p 00004000 1f:00 200        /lib/ld-uClibc-0.9.32.so
7f869000-7f88a000 rwxp 00000000 00:00 0          [stack]
7fff7000-7fff8000 r-xp 00000000 00:00 0          [vdso]

4. last 20 lines of cmd "strace pktCap"
fstat(3, {st_mode=S_IFREG|0755, st_size=482200, ...}) = 0
close(3)                                = 0
open("/lib/libgcc_s.so.1", O_RDONLY)    = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=1544533, ...}) = 0
close(3)                                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=482200, ...}) = 0
close(3)                                = 0
open("/lib/libc.so.0", O_RDONLY)        = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=482200, ...}) = 0
close(3)                                = 0
stat("/lib/ld-uClibc.so.0", {st_mode=S_IFREG|0755, st_size=22732, ...}) = 0
mprotect(0x775be000, 4096, PROT_READ)   = 0
mprotect(0x77430000, 4096, PROT_READ)   = 0
mprotect(0x7776c000, 4096, PROT_READ)   = 0
ioctl(0, TIOCNXCL, {B115200 opost isig icanon echo ...}) = 0
ioctl(1, TIOCNXCL, {B115200 opost isig icanon echo ...}) = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault

5. result of gdb:
root@ubuntu:/home/yc/code/gdb# ./mips-unknown-linux-uclibc-gdb ../files/pktCap 
GNU gdb (GDB) 7.3.1
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-pc-linux-gnu --target=mips-unknown-linux-uclibc".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/yc/code/files/pktCap...(no debugging symbols found)...done.
(gdb) target remote 192.168.1.1:1111
Remote debugging using 192.168.1.1:1111
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
0x771a8af0 in ?? ()
(gdb) x/11i $pc-5*4
   0x771a8adc:	lw	s0,24(sp)
   0x771a8ae0:	jr	ra
   0x771a8ae4:	addiu	sp,sp,48
   0x771a8ae8:	nop
   0x771a8aec:	nop
=> 0x771a8af0:	move	t9,ra
   0x771a8af4:	bal	0x771a8afc
   0x771a8af8:	nop
   0x771a8afc:	lui	gp,0x2
   0x771a8b00:	addiu	gp,gp,-15084
   0x771a8b04:	addu	gp,gp,ra
(gdb) info reg
          zero       at       v0       v1       a0       a1       a2       a3
 R0   00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
            t0       t1       t2       t3       t4       t5       t6       t7
 R8   00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
            s0       s1       s2       s3       s4       s5       s6       s7
 R16  7f8f0fd0 7f8f07d7 7f8f07e0 0092e0e8 7f8f0fd8 7f8f07e0 00000ff8 77bafe30 
            t8       t9       k0       k1       gp       sp       s8       ra
 R24  00000000 00000000 00000000 00000000 00000000 7f8893e0 7f8f07e0 00000000 
        status       lo       hi badvaddr    cause       pc
      00008d13 0001b0b9 000001c1 7f8ef7c8 00000020 771a8af0 
          fcsr      fir  restart
      00000000 00000000 00000000

**Comment by Koi-YC** [comment] 2021-04-15 12:38
@jreiser If you need other informations, please tell me.

**Comment by jreiser** [comment] 2021-04-18 23:28
```
(gdb) target remote 192.168.1.1:1111
Remote debugging using 192.168.1.1:1111
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
0x771a8af0 in ?? ()
(gdb) x/11i $pc-5*4
0x771a8adc: lw s0,24(sp)
0x771a8ae0: jr ra
0x771a8ae4: addiu sp,sp,48
0x771a8ae8: nop
0x771a8aec: nop
=> 0x771a8af0: move t9,ra
0x771a8af4: bal 0x771a8afc
0x771a8af8: nop
0x771a8afc: lui gp,0x2
0x771a8b00: addiu gp,gp,-15084
0x771a8b04: addu gp,gp,ra
```
This is the startup code for a new process, not the code at the time of the SIGSEGV.  If you are using gdbserver ("target remote ..."), then the first command to gdb must be `continue` which will start the program on the remote system.  Let the program run until it encounters the SIGSEGV, then capture the state as before (in https://github.com/upx/upx/issues/473#issuecomment-805795336).
The best way to enable the finding of a solution, is to send me a complete program which crashes, including all its private (non-system) shared libraries. For instance, create a small main program which just calls a subroutine in one shared library, such that there is a crash when using the UPX-compressed shared library. Then create a .tgz file of the program and the shared library, and attach that to an email.
I have setup `gdb` package on my MIPS-R3000 hardware (GL.iNet GL-AR300M, ar71xx/nand) using OpenWRT build system, and also setup a small test program which uses a private shared library.  The test program runs under OpenWRT 18.06.1, but crashes when run under `gdb`.

**Comment by Koi-YC** [comment] 2021-04-20 06:08
I have sent you new information，the complete program which crashes and all its private (non-system) shared libraries, please check the email.

**Comment by jreiser** [comment] 2021-04-21 01:53
Thank you for sending 473.tgz.  I have opened the archive and begun to look at libupnp.so.

**Comment by jreiser** [comment] 2021-04-24 21:12
Short answer: musl incompatibility.
Explanation: The UPX runtime decompression code for a shared library needs to know the actual page size, which is given by getauxval(AT_PAGESZ) and is not necessarily a constant across all hardware that implements a given architecture.  Looking up the function address of `getauxval` is inconvenient and expensive (particularly in space), so the runtime decompressor uses another technique.  The glibc code for the runtime linker ld-linux calls the DT_INIT (or _init) function with three arguments (argc, argv, env), and Linux puts the aux vector after the env vector.  The musl code for the runtime linker calls the DT_INIT (or _init) function with no arguments at all, which is the cause of the crash.
```
(gdb) x/11i $pc-5*4
   0x770f0b88:        addiu      sp,sp,-96
   0x770f0b8c:        sw   ra,92(sp)
   0x770f0b90:        sw   a2,80(sp)  // env
   0x770f0b94:        sw   a1,76(sp)  // argv
   0x770f0b98:        sw   a0,72(sp)  // argc
=> 0x770f0b9c:        lw    v0,0(a2)
   0x770f0ba0:        bnez       v0,0x770f0b9c  // find end of env
   0x770f0ba4:        addiu      a2,a2,4
   0x770f0ba8:        lw    v0,0(a2)  // look through auxv
   0x770f0bac:        li      v1,4096   // default page size if no AT_PAGESZ entry
   0x770f0bb0:       beqz       v0,0x770f0bc4
   0x770f0bb4:       addiu      v0,v0,-6   // -AT_PAGESZ
(gdb) info reg
         zero       at       v0       v1       a0       a1       a2       a3
R0   00000000 10008d01 00085b88 00000000 77200398 7706a488 00000000 00000000 
```

musl/ldso/dynlink.c:
```
#ifndef NO_LEGACY_INITFINI
        if ((dyn[0] & (1<<DT_INIT)) && dyn[DT_INIT])
            fpaddr(p, dyn[DT_INIT])();   /// arglist is empty
#endif
        if (dyn[0] & (1<<DT_INIT_ARRAY)) {
            size_t n = dyn[DT_INIT_ARRAYSZ]/sizeof(size_t);
            size_t *fn = laddr(p, dyn[DT_INIT_ARRAY]);
            while (n--) ((void (*)(void))*fn++)();   // arglist is empty
        }
```

glibc/elf/dl-init.c:
```
  if (ELF_INITFINI && l->l_info[DT_INIT] != NULL)
    DL_CALL_DT_INIT(l, l->l_addr + l->l_info[DT_INIT]->d_un.d_ptr, argc, argv, env);  // 3 args: argc, argv, env

  /* Next see whether there is an array with initialization functions.  */
  ElfW(Dyn) *init_array = l->l_info[DT_INIT_ARRAY];
  if (init_array != NULL)
    {
      unsigned int j;
      unsigned int jm;
      ElfW(Addr) *addrs;

      jm = l->l_info[DT_INIT_ARRAYSZ]->d_un.d_val / sizeof (ElfW(Addr));

      addrs = (ElfW(Addr) *) (init_array->d_un.d_ptr + l->l_addr);
      for (j = 0; j < jm; ++j)
    ((dl_init_t) addrs[j]) (argc, argv, env);   // 3 args: argc, argv, env
```

Investigating by hand using gdb on a "Hello world\n" program shows that the page size is 4096 on my device GL.iNet GL-AR300M, ar71xx/nand running OpenWRT 18.06.1.  What is the page size on your device?

**Comment by jreiser** [comment] 2021-04-29 02:30
It looks like it should be possible to find the page size by opening, reading, and closing `/proc/self/auxv`, which would be independent of glibc and musl.

**Comment by Koi-YC** [comment] 2021-04-29 03:53
I add some debug informations and rebuilded the project, it showed that the project used definition as below:
#ifdef CONFIG_PAGE_SIZE_4KB
#define PAGE_SHIFT      12
#endif

**Comment by markus-oberhumer** [comment] 2022-08-17 20:05
Is this fixed in current git?

**Comment by markus-oberhumer** [comment] 2022-10-06 09:17
@jreiser John please close if fixed

**Comment by jreiser** [comment] 2022-10-07 02:46
Believed fixed by `04c619859 (John Reiser             2021-05-07 09:36:07 -0700`.

**Closed by jreiser** 2022-10-07 02:46 UTC
