### ISSUE TITLE
Why not provide Darwin's static build?

### ISSUE THREAD

**Issue by xtqxk** [upx/upx#690] opened 2023-07-29 15:30 UTC
Brew is too big and slow.

**Comment by jreiser** [comment] 2023-07-29 16:10
```
$ type brew
brew: /opt/homebrew/bin/brew
$ file /opt/homebrew/bin/brew
/opt/homebrew/bin/brew: Bourne-again shell script text executable, ASCII text
$ ls -l /opt/homebrew/bin/brew
4677 bytes
```
So please do some digging and measurement to determine if there is any compiled binary executable program that is big and responsible for slowness.  Otherwise upx cannot help.

Edit: Also `otool -hl /bin/bash | grep vmsize` shows segments of 0x8c000, 0x4000, 0xc000, 0xc000 which is not so big.  And `otool -hl /bin/bash | grep ' name '` shows that the only required libraries are libncurses, libSysstem.B, and /usr/lib/dylib; again, not so large.

**Comment by markus-oberhumer** [comment] 2023-07-29 18:34
Duplicate of #555

**Closed as completed by markus-oberhumer** 2023-07-29 18:34 UTC
Labels: duplicate

**Comment by xtqxk** [comment] 2023-07-30 11:08
Ok ... Er.... Not everyone like to install the Brew's dependencies like 'xcode command line tools` there is my static build upx 4.0.2 darwin adm64, use base64 encode.
Usage :
1.  Download and  save the upx.txt 
2. `base64 -D -i ~/Downloads/upx.txt -o ~/Downloads/upx_bin`
3. `chmod u+x ~/Downloads/upx_bin`

[upx.txt](https://github.com/upx/upx/files/12209006/upx.txt)
