### ISSUE TITLE
Support for packing Windows AARCH64 executables?

### ISSUE THREAD

**Issue by CryptoManiac** [upx/upx#551] opened 2021-12-27 03:40 UTC
## What's the problem (or question)?
Unable to pack windows aarch64 executables. Are there any plans to add support for this feature?

```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: programd.exe: CantPackException: can't pack new-exe
upx: program-qt.exe: CantPackException: can't pack new-exe

Packed 0 files.
```

## What should have happened?
Something like this:

```
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   6749696 ->   2830848   41.94%    win64/pe     programd.exe                 
  22784000 ->   9992192   43.86%    win64/pe     program-qt.exe               
   --------------------   ------   -----------   -----------
  29533696 ->  12823040   43.42%                 [ 2 files ]

Packed 2 files.
```

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95
* Host Operating System and version: Ubuntu Linux 21.04
* Host CPU architecture: aarch64
* Target Operating System and version: Windows
* Target CPU architecture: aarch64

**Comment by jreiser** [comment] 2021-12-27 03:48
See also https://github.com/upx/upx/issues/502.

**Comment by markus-oberhumer** [comment] 2022-09-17 06:18
Duplicate of #502.

**Closed by markus-oberhumer** 2022-09-17 06:18 UTC
Labels: enhancement
