### ISSUE TITLE
UPX v4.2.2 - Compress Relocation Overflow

### ISSUE THREAD

**Issue by LordGarfio** [upx/upx#797] opened 2024-03-23 13:25 UTC
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

At the end of compression, a failure is shown: Relocation Overflow.

## What should have happened?

If you decompress the executable and then compress it, the compression should have ended without problems.

## Do you have an idea for a solution?

The decompression and compression process works perfectly with the UPX version 4.10 on the exeinfo PE V0.0.8.3.

## How can we reproduce the issue?

1. Download ExeInfo-PE v0.0.8.3 release from https://github.com/ExeinfoASL/ASL.
2. Look At 'OS: Windows XP/2003/7/8/10' Issue #9
3. Exactly: https://github.com/ExeinfoASL/ASL/issues/9#issuecomment-2016249974

## Please tell us details about your environment.

* UPX version 4.22
* Windows XP SP3 Home
* ISA x86-32 Bits

Regards.

![exeinfope_v0 0 8 3_Works](https://github.com/upx/upx/assets/65074751/e5889b90-22be-46ed-b696-c2e39622324e)
![exeinfope_v0 0 8 3_Fails](https://github.com/upx/upx/assets/65074751/db67d61f-bfb6-485e-b43a-58b2c9ee7a7f)

**Comment by jreiser** [comment] 2024-03-23 14:34
Same as https://github.com/upx/upx/issues/796 .  Earlier versions of upx had a bug which produced bad relocations beginning at position (1<<28: 256MiB).  Note that 356409874 is 0x153e6212, which does not fit in 28 bits.  The bad relocations often were undetected, even when running the compressed output, partly because the badly-relocated datums might reside in debugging info that was not executed.  The bug was detected in upx-4.2.x, producing the message about "relocation overflow" and exiting with failure status.

The underlying problem was fixed recently on upx branch `devel`.  Visit https://github.com/upx/upx/actions/runs/8383301434 to pick your favorite Artifact from the ContinuousIntegration build.

**Comment by markus-oberhumer** [comment] 2024-03-23 15:40
Duplicate of #796, fixed in `devel` branch.

**Closed as completed by markus-oberhumer** 2024-03-23 15:40 UTC
Labels: duplicate, os:Windows
