### ISSUE TITLE
Unpack failed ELF x86-64 "CantUnpackException: corrupt b_info"

### ISSUE THREAD

**Issue by LionNatsu** [upx/upx#635] opened 2022-12-02 09:43 UTC
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
We got some UPX packed virus samples, cannot unpack since somewhere after v3.96 till now (v4.0.1), and it was fine with v3.96.

## What should have happened?
They can be unpacked.

## Do you have an idea for a solution?
**Bisected to 78c555b4a63bb2bf7a9d827d9711aea0c31095b4**

    Handle old-style compressed main programs when de-compressing
    	modified:   p_lx_elf.cpp

We reverted this commit and UPX works again now.

## How can we reproduce the issue?

We have a lot of them. They were uploaded to VirusTotal years ago.
There are some of them:
- `3e4d7bb1f2d66b04a0ff13a98b55c318c9027e36fec72af4d23a77813f3bdc43`  3.94
- `84a07a58050966d87438fecf5b1ff64a073676ffe4c820e1439ee053bb441c2f`  3.95
- `05940ec51a57196b39f7913174fae7ec2e394f04ffaefc9f7bcf07c8da9bc747`  3.94

For your convenience, I downloaded those three file for you all for testing.
But keep in mind *DO NOT* run them, and they are ELF x86-64.

[upx-virus-cannot-unpack.zip](https://github.com/upx/upx/files/10139906/8473530576.zip)

## Please tell us details about your environment.

* UPX version used (`upx --version`): everything since 78c555b4a63bb2bf7a9d827d9711aea0c31095b4
* Host Operating System and version: unrelated, tested on both Linux and Windows
* Host CPU architecture: unrelated
* Target Operating System and version: UNIX, ELF
* Target CPU architecture: x86-64

**Comment by LionNatsu** [comment] 2022-12-02 09:45
ZIP password is `infected`, the default one from VirusTotal.

**Comment by markus-oberhumer** [comment] 2022-12-19 12:53
UPX is not a virus scanner.

**Comment by LionNatsu** [comment] 2022-12-19 13:50
True, UPX it's not a virus scanner. I mean, I just want to kindly help the upstream here to address a potential regression. I'm an employee in an anti-malware vendor (which has contacted UPX dev team earlier this year).

We now discovered this commit causes over 30% (which is a VERY huge amount) of ELF packed samples in our database now cannot be unpacked. Because the commit itself didn't explain what the "old-style" formats were, also because of the lack of test cases, I can only guess that it could be some tiny mistake in field size of `case Elf64_Ehdr::EM_X86_64:  sz_d_info = 2 * sizeof(unsigned); break` which, in the commit, changed from 6 to 2. Or is it intended, perhaps?

If it is a regression, I think we'd better reopening this to get the issue addressed. :smile_cat:

**Comment by LionNatsu** [comment] 2022-12-19 14:05
-- I do recognise that modified UPXes are not supported officially, which is not uncommon in malwares, but the 30%+ regression really rings a bell to me.

**Comment by jreiser** [comment] 2022-12-19 14:34
There was a change in the layout of compressed output, so `upx -d` must deal with both cases: the de-compressing stub code now can reside before or after the compressed gaps between PT_LOADs (and EOF).  The change was made for performance relative to fragmentation caused by page alignment, including in compressed shared libraries.  The commit intended to handle both layouts, but there are corner cases involving alignment, etc.
Using the test cases, I have identified the problem;, the solution is due Real Soon Now.

**Comment by markus-oberhumer** [comment] 2022-12-20 10:59
@LionNatsu I see, thanks for the info. Milestone 4.0.2 then.

**Comment by jreiser** [comment] 2022-12-20 15:42
Fixed by above commit https://github.com/upx/upx/commit/5c61279c618ba4516ac73b140202a83a7aa79d57 .

The 3e4d... and 84a0... cases are detected as modified-after-compression.  De-compression by `upx -d` gives warnings such as
```
[WARNING] bad b_info at 0x89f0

[WARNING] ... recovery at 0x89ec
```
Such recovery is a cat-and-mouse game played against an attacker.

**Comment by LionNatsu** [comment] 2022-12-20 21:45
Cool! So the fix is, because `b_info.sz_unc` should contain the right size of LOAD-gap, now it will find the LOAD-gap size around the ideal (?) position `pos`, within a radius of `N_PEEK(64) / 2` bytes to determine where the actual `b_info` was, am I right?

https://github.com/upx/upx/blob/50fc2b31cad58a7833e8a890dbd32af6431e183d/src/p_lx_elf.cpp#L5416-L5421

The second `seek` does the same job as the first one, isn't it? The expression looks a little bit wordy 😵‍💫 

Nitpits: indention of these lines looks not quite right... Starting from the open bracket with a comment at L5408.

https://github.com/upx/upx/blob/50fc2b31cad58a7833e8a890dbd32af6431e183d/src/p_lx_elf.cpp#L5401-L5442

**Comment by LionNatsu** [comment] 2022-12-20 21:55
And just by the way, the typo fix from `phdr[]` to `phdri[]` (at L5373) sounds like a real bug fix for unpacking something... (but I don't really know) Is it related to this issue?

https://github.com/upx/upx/blob/50fc2b31cad58a7833e8a890dbd32af6431e183d/src/p_lx_elf.cpp#L5369-L5378

The `phdr[]` line was introduced in 963392a5ae02fb78c788e0ba07a516964c6919c7 "De-compress (upx -d) for ELF pageholes" affecting v3.99+

**Comment by jreiser** [comment] 2022-12-20 22:20
@LionNatsu   `... am I right?` Yes.

```
 fi->seek(pos - H_PEEK, SEEK_SET); 
 fi->readx(peek_arr, sizeof(peek_arr)); 
 fi->seek(pos + H_PEEK - sizeof(peek_arr), SEEK_SET);
```
The expected position of the `b_info` block is the current position `pos`. The `seek` at line 5418 moves backwards by H_PEEK. Then the `readx` moves forwards by `sizeof(peek_arr)`.  Then the `seek`at line  5420 moves backwards to the original position before line 5418.  The argument for the second `seek` could be just `pos`; the current code emphasizes that the last `seek` reverses the positioning effect of the `readx` and the first `seek`.

The (non-)indentation is a visual highlighting.  It may get removed after a while for some cleanup. `word1` etc are a reaction to `clang` complaint about increased alignment when casting from `byte *` to `b_info *`. 

 The typo fix from `phdr[]` to` phdri[]` might not be specific to this issue #635, but it is related to finding the compressed gaps between PT_LOADs, which is the general problem here.

**Comment by LionNatsu** [comment] 2022-12-20 22:33
> ... Then the `seek`at line 5420 moves backwards to the original position before line 5418. The argument for the second `seek` could be just `pos`; ...

@jreiser You mean `fi->seek(pos + H_PEEK - sizeof(peek_arr), SEEK_SET);` is actually `fi->seek(pos + H_PEEK - H_PEEK, SEEK_SET);` so it equals to `fi->seek(pos, SEEK_SET);`?

Wait a second... `sizeof(peek_arr)` is `N_PEEK` not `H_PEEK` (actually twice as `H_PEEK`!)

**Comment by jreiser** [comment] 2022-12-20 22:44
@LionNatsu  You have the examples: just step through it.  On Linux you can let the OS help:
```
(gdb) info proc   ## note the process ID
(gdb) shell cat /proc/PID/fdinfo/3
```

**Comment by LionNatsu** [comment] 2022-12-21 00:00
@jreiser It does go back to the `pos - H_PEEK` instead of `pos`.

```
Breakpoint 2, PackLinuxElf64::unpack (this=0x555555a0dab0, fo=0x7fffffffd940) at /root/upx/src/p_lx_elf.cpp:5418
5418                    fi->seek(pos - H_PEEK, SEEK_SET);
(gdb) shell cat /proc/`pgrep upx`/fdinfo/3
pos:    35312
flags:  0100000
mnt_id: 25
(gdb) p H_PEEK
$3 = 32
(gdb) n
5419                    fi->readx(peek_arr, sizeof(peek_arr));
(gdb) shell cat /proc/`pgrep upx`/fdinfo/3
pos:    35280
flags:  0100000
mnt_id: 25
(gdb) n
5420                    fi->seek(pos + H_PEEK - sizeof(peek_arr), SEEK_SET);
(gdb) shell cat /proc/`pgrep upx`/fdinfo/3
pos:    35344
flags:  0100000
mnt_id: 25
(gdb) n
5421                    int boff = find_le32(peek_arr, sizeof(peek_arr), size);
(gdb) shell cat /proc/`pgrep upx`/fdinfo/3
pos:    35280
flags:  0100000
mnt_id: 25
(gdb) p sizeof(peek_arr)
$4 = 64
(gdb)
```

**Comment by LionNatsu** [comment] 2022-12-21 00:22
Well, it will not change the last result in these cases though. When the `b_info` can be found in `peek_arr`, the later "recovery" `fi->seek(..., SEEK_SET);` will effectively override the side effect of previous (second) seek we are talking about.

But when the magic size word can't be found, it will "let go" with a file cursor points to `pos - 32`

**Closed as completed** 2022-12-22 14:09 UTC
Labels: os:Linux
