### ISSUE TITLE
Compressed executables are killed by macOS zsh

### ISSUE THREAD

**Issue by ttc0419** [upx/upx#786] opened 2024-02-12 12:26 UTC
## What's the problem (or question)?
Compressed executables are killed by macOS zsh.

## What should have happened?
Executables should work as intended

## Do you have an idea for a solution?
Nope

## How can we reproduce the issue?
1. Create a basic hello world C program
```c
#include <stdio.h>

int main(void)
{
    puts("Hello world!");
    return 0;
}
```
2. ```clang hello.c```
4. ```upx a.out```
5. Run the executable
```
[u@mbp d](master)% ./a.out 
zsh: killed     ./a.out
```

## Please tell us details about your environment.

* UPX version used (`upx --version`):
```
upx 4.1.0
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.11
Copyright (C) 1996-2023 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2023 Laszlo Molnar
Copyright (C) 2000-2023 John F. Reiser
Copyright (C) 2002-2023 Jens Medoch
Copyright (C) 1995-2023 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2023 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host and Target CPU architecture and Operating System version:
```
Darwin 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:30 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8122 arm64
```

**Comment by markus-oberhumer** [comment] 2024-02-12 14:43
Unfortunately UPX compressed binaries currently do not work on macOS 13 or later, thanks to undocumented changes by Apple.

Closing as duplicate of https://github.com/upx/upx/issues/612

**Closed as not planned by markus-oberhumer** 2024-02-12 14:43 UTC
Labels: duplicate, os:macOS
