### ISSUE TITLE
ELF ::canUnpack() should detect truncated compressed file

### ISSUE THREAD

**Issue by satmandu** [upx/upx#712] opened 2023-09-20 14:03 UTC
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?

```
Attempting to compress /usr/local/tmp/crew/dest/usr/local/bin/llvm-strip ...
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
visitAllPackers: (ver=14, fmt= 25) PackFreeBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackNetBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackOpenBSDElf32x86
visitAllPackers: (ver=14, fmt= 12) PackLinuxElf32x86
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/tmp/crew/dest/usr/local/bin/llvm-strip-crewupxtmp: CantPackException: corrupted file; details: bytes > 0 (/usr/local/tmp/crew/upx.20230920133931.dir/src/util/membuffer.cpp: alloc: 203)
```

## What should have happened?
Not getting this error on linux/armv7l

## How can we reproduce the issue?

1. Binaries being compressed are inside https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm17_build/17.0.1_x86_64/llvm17_build-17.0.1-chromeos-x86_64.tar.zst inside `/usr/local/bin` using `upx --debug --lzma`

## Please tell us details about your environment.

* UPX version used (`upx --version`): 
```
upx --version
upx 4.1.0
UCL data compression library 1.03
zlib data compression library 1.2.13.1-motley
LZMA SDK version 4.43
doctest C++ testing framework version 2.4.11
Copyright (C) 1996-2023 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2023 Laszlo Molnar
Copyright (C) 2000-2023 John F. Reiser
Copyright (C) 2002-2023 Jens Medoch
Copyright (C) 1995-2023 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
Copyright (C) 2016-2023 Viktor Kirilov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'upx -L'.
```
* Host Operating System and version: `Ubuntu 23.10, kernel 6.6-rc1` 
* Host CPU architecture: `x86_64`
* Target Operating System and version: `ChromeOS Milestone 90 container` 
* Target CPU architecture: `x86_64`

**Comment by jreiser** [comment] 2023-09-20 14:39
Please give the (an) actual command line which fails.  I don't see anything wrong.  The `.tar.zst` file contains many exeucatbles that are already compressed by upx, and which can be de-compressed by upx:
```
$ zstdcat llvm17_build-17.0.1-chromeos-x86_64.tar.zst | tar xf -   ## extract the uploaded archive
$ file $(find . -name '*strip*')   ## look for suspect file
./usr/local/bin/llvm-bitcode-strip: symbolic link to llvm-objcopy
./usr/local/bin/llvm-strip:         symbolic link to llvm-objcopy
$ file $(find . -name llvm-objcopy)
./usr/local/bin/llvm-objcopy: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), statically linked, no section header

$ readelf --all ./usr/local/bin/llvm-objcopy   ## inspect this file
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              DYN (Shared object file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x3bbe8
  Start of program headers:          64 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         3
  Size of section headers:           0 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

There are no section groups in this file.

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000001000 0x000000000002f2e8  RW     0x1000
  LOAD           0x0000000000000000 0x0000000000030000 0x0000000000030000
                 0x000000000000cfcc 0x000000000000cfcc  R E    0x1000
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10

There is no dynamic section in this file.

There are no relocations in this file.
No processor specific unwind information to decode

Dynamic symbol information is not available for displaying symbols.

No version information found in this file.

$ upx -d -f -o bar ./usr/local/bin/llvm-objcopy   ## de-compress the packed llvm-objcopy
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX git-XXXXXX  Markus Oberhumer, Laszlo Molnar & John Reiser   Sep 12th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    195152 <-     53772   27.55%   linux/amd64   bar

Unpacked 1 file.
$ 
```

**Comment by satmandu** [comment] 2023-09-20 14:45
OMG. This may be an error message I'm getting from attempting **recompression**, whereas attempting **recompression** on armv7l isn't failing for some reason. I'll close this...

**Comment by markus-oberhumer** [comment] 2023-09-20 18:54
Are we missing a proper `AlreadyPackedException` in some cases? If yes, then please reopen.

**Comment by markus-oberhumer** [comment] 2023-09-20 20:32
John please have a look (and change the title of this issue accordingly).

**Comment by satmandu** [comment] 2023-09-20 20:39
I'm thinking that the arm files Should have given an exception?

Let me find a link to that archive...

**Comment by jreiser** [comment] 2023-09-20 20:46
@satmandu A reproducible test case is required.  What was the actual command line that failed?

I have tried re-compressing all the executables (most of them already compressed) in `./usr/local/bin` and `./usr/local/libexec`.  They all get one of the diagnoses `AlreadyPackedException`, `IOException: is a symlink -- skipped`, or `CantPackException: file is too small`.

From the original Description, `... usr/local/bin/llvm-strip-crewupxtmp: CantPackException: corrupted file; ...` it looks like there may have been simultaneous competing  compression (two command streams [shell scripts] running at the same time), because of the substring `upxtmp: CantPack` where `upxtmp` is part of the name of a temporary file used by upx.

**Comment by satmandu** [comment] 2023-09-20 21:01
The upxtmp algorithm just compresses with upx to a temp file, and then decompresses, and only copies over the original if the decompress succeeds.

It looks like armv7l is correctly giving me the already packed exception:
```
chronos@rpi4b-armv7l /usr/local/lib/crew/packages $ upx --debug --lzma /usr/local/bin/llvm-strip
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
visitAllPackers: (ver=14, fmt= 25) PackFreeBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackNetBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackOpenBSDElf32x86
visitAllPackers: (ver=14, fmt= 12) PackLinuxElf32x86
visitAllPackers: (ver=14, fmt= 22) PackLinuxElf64amd
visitAllPackers: (ver=14, fmt= 23) PackLinuxElf32armLe
  decodePackHeaderFromBuf  version=14  format=23  method=14  level=8
upx: /usr/local/bin/llvm-strip: AlreadyPackedException

Packed 0 files.
```
On x86_64 I am seeing this:
```
chronos@cheekon-x86_64 /usr/local/lib/crew/packages $ upx --debug --lzma /usr/local/bin/llvm-strip
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.0.3       Markus Oberhumer, Laszlo Molnar & John Reiser    Feb 5th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt=129) PackTos
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
visitAllPackers: (ver=14, fmt= 25) PackFreeBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackNetBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackOpenBSDElf32x86
visitAllPackers: (ver=14, fmt= 12) PackLinuxElf32x86
upx: /usr/local/tmp/crew/upx.20230305034655.dir/src/util/membuffer.cpp:199: void MemBuffer::alloc(upx_uint64_t): Assertion `bytes > 0' failed.
Aborted (core dumped)
```

**Comment by satmandu** [comment] 2023-09-20 21:06
Interestingly on i686 I get a different message, but that's because the compression failed in the first place:
```
chronos@cheekon-i686 /usr/local/lib/crew/packages $ upx --debug --lzma /usr/local/bin/llvm-strip
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
upx: /usr/local/bin/llvm-strip: CantPackException: bad PT_LOAD phdr[1]

Packed 0 files.
chronos@cheekon-i686 /usr/local/lib/crew/packages $ upx -d /usr/local/bin/llvm-strip
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: /usr/local/bin/llvm-strip: CantUnpackException: bad PT_LOAD phdr[1]

Unpacked 0 files.
```

**Comment by jreiser** [comment] 2023-09-20 22:51
@satmandu  So please state a link to the i686 file which fails, or a link to the archive which contains the i686 file which fails.

**Comment by satmandu** [comment] 2023-09-21 01:33
So this appears to be an edge case.

We run `llvm-strip` before running `upx` to compress.

For our llvm packaging, we are running a second packaging step to break up our initial large build package into smaller packages.

That is causing our initially packaged llvm-stripped and upx compressed binaries to have llvm-strip run on it a second time before passing the binary to upx, a second time. _It is only then we get these error messages._

Running llvm-strip (llvm-objcopy) on a upx compressed binary appears creates a binary which upx does recognize as compressed. _I think that's the crux of the issue_.

I will set these secondary packages to not strip or compress, but I think that's why these messages are cropping up.

```
chronos@cheekon-i686 /usr/local/tmp $ curl -OLf https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm17_build/17.0.1_i686/llvm17_build-17.0.1-chromeos-i686.tar.zst
chronos@cheekon-i686 /usr/local/tmp $ sha256sum llvm*
80dc613b746126b1b393aaef98078a245f7f25d89b65de1b599f755352e21996  llvm17_build-17.0.1-chromeos-i686.tar.zst
chronos@cheekon-i686 /usr/local/tmp $ zstdcat llvm17_build-17.0.1-chromeos-i686.tar.zst | tar xf -
chronos@cheekon-i686 /usr/local/tmp $ file ./usr/local/bin/llvm-objcopy
./usr/local/bin/llvm-objcopy: ELF 32-bit LSB pie executable, Intel 80386, version 1 (GNU/Linux), statically linked, no section header
chronos@cheekon-i686 /usr/local/tmp $ cp ./usr/local/bin/llvm-objcopy ./usr/local/bin/llvm-objcopy.orig
chronos@cheekon-i686 /usr/local/tmp $ ./usr/local/bin/llvm-objcopy ./usr/local/bin/llvm-objcopy
chronos@cheekon-i686 /usr/local/tmp $ sha256sum ./usr/local/bin/llvm-objcopy
b4292ebdebfd55472b58943e566a1eaa80628a3e02d0523f8aedcffce6e3bc9b  ./usr/local/bin/llvm-objcopy
chronos@cheekon-i686 /usr/local/tmp $ sha256sum ./usr/local/bin/llvm-objcopy.orig 
c8c57c92eafe586a2cb05a0323a243292eae1f0a4b4fef22380c753a160a68c2  ./usr/local/bin/llvm-objcopy.orig
chronos@cheekon-i686 /usr/local/tmp $ upx -f -o foo --lzma --debug ./usr/local/bin/llvm-objcopy
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
upx: ./usr/local/bin/llvm-objcopy: CantPackException: bad PT_LOAD phdr[1]

Packed 0 files.
chronos@cheekon-i686 /usr/local/tmp $ upx -f -o foo --lzma --debug ./usr/local/bin/llvm-objcopy.orig
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
visitAllPackers: (ver=14, fmt= 25) PackFreeBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackNetBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackOpenBSDElf32x86
visitAllPackers: (ver=14, fmt= 12) PackLinuxElf32x86
  decodePackHeaderFromBuf  version=14  format=12  method=14  level=8
upx: ./usr/local/bin/llvm-objcopy.orig: AlreadyPackedException

Packed 0 files.
chronos@cheekon-i686 /usr/local/tmp $
```

Deciding whether or not to deal with `upx` compressed binaries, that have then been run through strip (which is, of course, insane) is something I leave to your discretion.

In regards to x86_64, it looks like we just aren't seeing the `AlreadyPackedException` whether the upx compressed binary is stripped or not. :

```
chronos@cheekon-x86_64 /usr/local/tmp $ curl -OLf https://gitlab.com/api/v4/projects/26210301/packages/generic/llvm17_build/17.0.1_x86_64/llvm17_build-17.0.1-chromeos-x86_64.tar.zst
chronos@cheekon-x86_64 /usr/local/tmp $ sha256sum llvm* sha256sum llvm*

eebc943cc0c7a7d5528c143a5c0188a16486408dad029123cf644b543be30b22  llvm17_build-17.0.1-chromeos-x86_64.tar.zst
chronos@cheekon-x86_64 /usr/local/tmp $ zstdcat llvm17_build-17.0.1-chromeos-x86_64.tar.zst | tar xf -

chronos@cheekon-x86_64 /usr/local/tmp $ file ./usr/local/bin/llvm-objcopy

./usr/local/bin/llvm-objcopy: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), statically linked, no section header
chronos@cheekon-x86_64 /usr/local/tmp $ cp ./usr/local/bin/llvm-objcopy ./usr/local/bin/llvm-objcopy.orig

chronos@cheekon-x86_64 /usr/local/tmp $ ./usr/local/bin/llvm-objcopy ./usr/local/bin/llvm-objcopy

chronos@cheekon-x86_64 /usr/local/tmp $ sha256sum ./usr/local/bin/llvm-objcopy

2550fef8fc0bf14d069276f54390ebf58774721818b7c4873ff7df8f1248f78e  ./usr/local/bin/llvm-objcopy
chronos@cheekon-x86_64 /usr/local/tmp $ sha256sum ./usr/local/bin/llvm-objcopy.orig
sha256sum ./usr/local/bin/llvm-objcopy.orig

8873254ffe57232f3599056221868d881e8f7b2caa207330504bb62ae8030984  ./usr/local/bin/llvm-objcopy.orig
chronos@cheekon-x86_64 /usr/local/tmp $ upx -f -o foo --lzma --debug ./usr/local/bin/llvm-objcopy

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
visitAllPackers: (ver=14, fmt= 25) PackFreeBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackNetBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackOpenBSDElf32x86
visitAllPackers: (ver=14, fmt= 12) PackLinuxElf32x86
upx: ./usr/local/bin/llvm-objcopy: CantPackException: corrupted file; details: bytes > 0 (/usr/local/tmp/crew/upx.20230920133931.dir/src/util/membuffer.cpp: alloc: 203)

Packed 0 files.
chronos@cheekon-x86_64 /usr/local/tmp $ upx -f -o foo --lzma --debug ./usr/local/bin/llvm-objcopy.orig

                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
visitAllPackers: (ver=14, fmt=  4) PackDjgpp2
visitAllPackers: (ver=13, fmt=  8) PackTmt
visitAllPackers: (ver=13, fmt=  5) PackWcle
visitAllPackers: (ver=13, fmt= 36) PackW64PeAmd64
visitAllPackers: (ver=13, fmt=  9) PackW32PeI386
visitAllPackers: (ver=13, fmt= 21) PackWinCeArm
visitAllPackers: (ver=13, fmt=  3) PackExe
visitAllPackers: (ver=13, fmt= 28) PackVmlinuxARMEL
visitAllPackers: (ver=13, fmt=135) PackVmlinuxARMEB
visitAllPackers: (ver=13, fmt=136) PackVmlinuxPPC32
visitAllPackers: (ver=13, fmt= 40) PackVmlinuxPPC64LE
visitAllPackers: (ver=13, fmt= 27) PackVmlinuxAMD64
visitAllPackers: (ver=13, fmt= 19) PackVmlinuxI386
visitAllPackers: (ver=13, fmt= 15) PackVmlinuzI386
visitAllPackers: (ver=13, fmt= 16) PackBvmlinuzI386
visitAllPackers: (ver=13, fmt= 31) PackVmlinuzARMEL
visitAllPackers: (ver=14, fmt= 25) PackFreeBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackNetBSDElf32x86
visitAllPackers: (ver=14, fmt= 25) PackOpenBSDElf32x86
visitAllPackers: (ver=14, fmt= 12) PackLinuxElf32x86
upx: ./usr/local/bin/llvm-objcopy.orig: CantPackException: corrupted file; details: bytes > 0 (/usr/local/tmp/crew/upx.20230920133931.dir/src/util/membuffer.cpp: alloc: 203)

Packed 0 files.
chronos@cheekon-x86_64 /usr/local/tmp $ upx -d ./usr/local/bin/llvm-objcopy.orig
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
    195152 <-     53772   27.55%   linux/amd64   llvm-objcopy.orig

Unpacked 1 file.
chronos@cheekon-x86_64 /usr/local/tmp $ upx -d ./usr/local/bin/llvm-objcopy
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2023
UPX 4.1.0       Markus Oberhumer, Laszlo Molnar & John Reiser    Aug 8th 2023

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
upx: ./usr/local/bin/llvm-objcopy: CantUnpackException: bad PT_LOAD phdr[1]

Unpacked 0 files.
```

**Comment by jreiser** [comment] 2023-09-21 16:19
@satmandu  Thank you for the reproducible test case!  It might take 5 or 10 minutes longer to compose, but a reproducible test case  shortens debugging time by **HOURS**.  I especially appreciate using sha256sum to provide guideposts to insure that everyone is dealing with the same file contents. Continuous Integration can produce too many impostors that are very similar but not necesssarily exactly the same.

**Comment by jreiser** [comment] 2023-09-21 16:23
@markus-oberhumer The trigger is applying `llvm-strip` to the output from upx.  llvm-strip discards anything that is not covered by a PT_LOAD.  This means that applying `upx -d` de-compression cannot re-construct the gaps between PT_LOAD, the debug symbol table, etc.  In particular, llvm-strip lops off the 36-byte trailing PackHeader at EOF  that contains checksums and other important data.  This means that` ::canUnpack()` cannot `::find_overlay_offset()`, so the conclusion is "not packed by UPX".  Therefore the packers for the various file formats continue attempting to pack, which produces the "strange" warnings and errors.  I'm working on adding a strong heuristic so that `::canUnpack()` will detect such a case, and `throw` sooner, with a message such as "compressed input file has been truncated".  Security note: the output from llvm-strip on a packed executable still runs, but the original file cannot be recovered by `upx -d`.  So llvm-strip removes a "security seal", and thus facilitates creating malware.  Perhaps the upx output format for compressed ELF should have near the beginning a second copy of the PackHeader, much like a GPT-format storage medium has info at both the beginning and the end.

**Comment by jreiser** [comment] 2023-09-21 21:33
Fixed by above commit.

**Closed as completed by jreiser** 2023-09-21 21:33 UTC
Labels: os:Linux
