### ISSUE TITLE
GraalVM-compiled exe does not run after being compressed with UPX.

### ISSUE THREAD

**Issue by su-404** [upx/upx#831] opened 2024-06-09 14:58 UTC
What's the problem (or question)?

GraalVM-compiled exe does not run after being compressed with UPX.

What should have happened?

The compressed exe should run without issues.

Do you have an idea for a solution?

Possible incompatibility with GraalVM or need for special UPX parameters.

How can we reproduce the issue?

Compile an exe with GraalVM.
Compress the exe with UPX.
Run the compressed exe.
Observe the failure to run.

Please tell us details about your environment.

UPX version used (upx --version): 4.2.4
Host Operating System and version: Windows 10
Host CPU architecture: Intel i7
Target Operating System and version: Windows 10
Target CPU architecture: Intel i7

**Comment by jreiser** [comment] 2024-06-09 15:14
You must supply an actual .exe executable file ("Paste, drop, or click to add files"; or a downloadable URL) which fails after compression. Your recipe is not reproducible.

**Comment by su-404** [comment] 2024-06-09 15:31
[Hello.zip](https://github.com/user-attachments/files/15753101/Hello.zip)
Here's my executable.

**Comment by markus-oberhumer** [comment] 2024-06-09 16:30
Duplicate of #559 and #670.

**Comment by jreiser** [comment] 2024-06-10 16:15
Yes, apparently duplicate GraalVM environment (versions?).  But the code for this  testcase might be simpler to understand, although the file is not the smallest:
   #831   ` 24MB  Hello.exe`
  #670   `143MB  demo.exe`
  #559    ` 12MB  NativeImageUsingJPMS-windows.exe`

**Comment by su-404** [comment] 2024-06-10 22:04
Yes, I'm having the same problem as them. Here's my code, the output is the simplest version, with other dependencies in the singular. I tried using the latest version of GraalVM.![image](https://github.com/upx/upx/assets/81111471/a20d255b-b05c-4d74-807d-aefdc5f4a0cf)
![image](https://github.com/upx/upx/assets/81111471/727e880e-2cf2-45a3-8fc0-6f5d7d1ffa65)



> 是的，显然是重复的GraalVM环境（版本？但是这个测试用例的代码可能更容易理解，尽管文件不是最小的：#831 #670 #559` 24MB Hello.exe``143MB demo.exe` ` 12MB NativeImageUsingJPMS-windows.exe`

**Comment by markus-oberhumer** [comment] 2024-06-10 23:26
This is a GraalVM bug introduced in Graal version 22.

See https://github.com/upx/upx/issues/559#issuecomment-1032047038 and #670 for some technical details.

And complain at https://github.com/oracle/graal/issues/4340 or https://github.com/oracle/graal/issues/7605 .

**Closed as not planned by markus-oberhumer** 2024-06-10 23:26 UTC
Labels: duplicate, os:Windows, notabug
