### ISSUE TITLE
Program compressed with UPX 3.95 wont start on some machines

### ISSUE THREAD

**Issue by Daniel-Tr** [upx/upx#253] opened 2019-02-21 11:35 UTC
## What's the problem (or question)?

Program (32bit build) compressed with UPX V3.95 fails to start on some machines running Windows 10. The process terminates with an error dialog 'The application was unable to start correctly (0xC0000005)'. The Windows event log does not contain any further information.
The error does not occur on all machines, but is reproducible on the machines affected.
Running the exact same executable compressed with UPX V3.91 works as expected.

Potentially related to: https://github.com/upx/upx/issues/52

## What should have happened?

I would expect the program to start without the exception to occur.

## Do you have an idea for a solution?

Unfortunately, no.

## How can we reproduce the issue?

1. Start application.

To be precise: We were not yet able to reproduce this issue on our systems, hindering us unfortunately from detailed analysis on the target system.

The affected application is attached to here, but the error occurred with other builds and applications as well (so: If a host is affected, it is affected. The application itself seems to be irrelevant)
[TreeSizeFree-Portable-v4.3.1.392.zip](https://github.com/upx/upx/files/2889065/TreeSizeFree-Portable-v4.3.1.392.zip)

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.95w
* Host Operating System and version: Windows 10, 17134
* Host CPU architecture: x64
* Target Operating System and version: Windows 10, 17134/multiple
* Target CPU architecture: x64

**Comment by jreiser** [comment] 2019-02-21 13:34
Regarding `If a host is affected, it is affected. The application itself seems to be irrelevant`, please confirm that notepad.exe is affected when compressed with upx-3.95; and show the Version of notepad.exe, and its filesize in bytes before compression.

**Comment by Daniel-Tr** [comment] 2019-02-21 15:21
A compressed notepad.exe fails with error 'Wrong parameter'.
Decompressing this file again, the application fails with error message 'Die Anwendung konnte nicht korrekt gestartet werden (0xc000007b). Klicken Sie auf "OK", um die Anwendung zu schließen.'

Applies to both, UPX V3.91 and V3.95.
Tested with notepad.exe version: 10.0.17134.131, Size: 245.760 Bytes

(I don't think this is the same issue ..)

**Comment by alexey-kleymenov** [comment] 2020-08-24 19:20
Hello! Do you have any updates on this issue? Steps to reproduce:
1) compress standard calc.exe on Windows 10 x64 using UPX 3.96 x64
2) try to run it

**Comment by Tronmech** [comment] 2022-08-25 19:25
I've had this happen with x64 compressed executables, as well as UPX itself. I believe that -- at least in my case -- the issue is caused by one or more of:

- Carbon Black
- Websense Forcepoint DLP
- Digital Guardian 
- Crowdstrike Falcon

Or the policies set in one of those. I know that Forcepoint uses DLL injection to monitor executables (likely injecting an interposing library). I'm not sure about the others. I expect one or more of those also insert foreign threads to watch what the tool is doing.

**Comment by markus-oberhumer** [comment] 2022-11-03 20:43
What is the status of this issue? Is this an UPX bug, or is this related to #437 ?

**Comment by jreiser** [comment] 2022-11-03 22:50
This is a Windows issue, complicated by Other Actors who think they know what is going on and stick their fingers in the pie without considering all the details.  It is unlikely to get resolved until the exact execution environment is nailed down, and the details analyzed by experts of `all `the Actors (including UPX).

**Comment by markus-oberhumer** [comment] 2022-11-03 22:56
Ok, closing as invalid then.

**Closed by markus-oberhumer** 2022-11-03 22:56 UTC
Labels: bug, Windows10

**Comment by HarikrishnanBalagopal** [comment] 2023-06-09 11:57
> This is a Windows issue, complicated by Other Actors who think they know what is going on and stick their fingers in the pie without considering all the details. It is unlikely to get resolved until the exact execution environment is nailed down, and the details analyzed by experts of `all `the Actors (including UPX).

Also happens on MacOS Ventura 13.4 (22F66) with Crowdstrike. When the binary is executed it prints
```shell
$ ls bin/
move2kube-api
$ ./bin/move2kube-api version -l
Killed: 9
$ ./bin/move2kube-api version -l
-bash: ./bin/move2kube-api: No such file or directory
```
and exits, the binary also gets deleted.

https://developer.apple.com/forums/thread/51828

Fixed by removing UPX https://github.com/konveyor/move2kube-api/pull/145

**Comment by markus-oberhumer** [comment] 2023-06-09 17:00
The relevant macOS 13 issue is #612
