### ISSUE TITLE
InternalError: should not happen

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#168] opened 2018-01-05 08:45 UTC
## What's the problem (or question)?

failed to compress executable
## What should have happened?

compressed exe
## Do you have an idea for a solution?

nope
## How can we reproduce the issue?

1.compress attached exe
2.
3.
4.

## Please tell us details about your environment.

* UPX version used (`upx --version`):3.94
* Host Operating System and version:10 64
* Host CPU architecture:x64
* Target Operating System and version:10 64
* Target CPU architecture:x64
[1.zip](https://github.com/upx/upx/files/1605957/1.zip)

**Comment by Oldes** [comment] 2018-01-16 13:36
I have the same problem.. UPX version 3.08, which I was using until now was able to compress given exe file.

**Comment by dockimbel** [comment] 2018-03-14 12:07
Same problem here, it was working fine a few versions ago (unsure which one was the last good one). Please find attached the test file that is causing the `InternalError` on upx 3.94.
[gui-console.zip](https://github.com/upx/upx/files/1810938/gui-console.zip)

**Comment by BeardPower** [comment] 2018-03-20 22:56
The issue is related to empty names in the import lookup table. A fixe is proposed here:
[Proposed fix](https://github.com/upx/upx/issues/69#issuecomment-325868625)

**Comment by necros2k7** [comment] 2018-03-22 07:31
how soon will this fix be in binary?

**Comment by Mattiwatti** [comment] 2018-11-14 15:33
@necros2k7 See #223 for a link with binaries that fix this if you are using 64 bit Windows (otherwise you will have to compile one of the two source trees yourself).

The binaries are UPX 3.95 from the current `devel` branch (473b904 + the fix commit to be precise).

**Comment by pmdesigner** [comment] 2019-11-25 10:11
Upx3.95 also has this error
[test.zip](https://github.com/upx/upx/files/3886034/test.zip)

**Comment by xrayer** [comment] 2020-11-02 03:20
UPX 3.96 still same...

**Comment by necros2k7** [comment] 2021-03-13 06:00
https://github.com/upx/upx-automatic-builds/tree/devel-20201206-830b242-appveyor still error (

**Comment by jreiser** [comment] 2021-03-13 19:50
The comment https://github.com/upx/upx/issues/69#issuecomment-798773340 explains that a patch to fix the compression side is available, but the de-compression side still does not work.  De-compression must work before there can be a release, else UPX becomes a tool that can hide malware.  This would affect even legitimate uses of UPX, because some administrators adopt the simplistic policy of "anything that `might be` or `facilitates` malware may not run on our systems."
Meanwhile the PullRequest  https://github.com/upx/upx/pull/470 has been merged, so auto-builds wlll produce more artifacts that can be downloaded.

**Closed** 2021-09-08 12:06 UTC
Labels: Windows10
