### ISSUE TITLE
Go program panics during init

### ISSUE THREAD

**Issue by anacrolix** [upx/upx#839] opened 2024-07-19 03:26 UTC
From https://github.com/golang/go/issues/68268#issuecomment-2237014814.

Demo exe: https://github.com/golang/go/issues/68268#issuecomment-2210210339.

Repo for reproduction and description of behaviour: https://github.com/golang/go/issues/68268#issuecomment-2208229720.

Description of failure: https://github.com/golang/go/issues/68268#issue-2385024829.

TLDR: Go program compiled for Windows amd64 and run on ARM64 panics while initing regexp, possibly due to resources not being mapped correctly.

**Comment by anacrolix** [comment] 2024-08-12 06:18
Hello, is there anything I can do to help with this? Thanks for the awesome project.

**Comment by jreiser** [comment] 2024-08-12 19:22
@anacrolix The setup seems to be not simple. The debugging strategy is to remove complication.
1. Please confirm the development path:  Go-language source code ==> Go-compiled and built for WIndows 11 x86_64 ==> compressed by UPX ==> run on Windows 11 ARM64 ==> complaint by Go runtime.
2. Does the compressed-by-UPX code run without complaint on Windows 11 x86_64? If so, then the machinery which emulates Windows 11 x86_64 on Windows 11 ARM64 becomes a prime suspect, although the Go runtime support could contribute.
3. When the Go source is compiled and built directly for, and run on, Windows 11 ARM64, then does the Go runtime complain?  If so, then the problem lies in the Go source, or the Go compile-and-build machinery, or the Go runtime.  (Compression by UPX is not a problem source.)
4. Use general low-level debugging tools for WIndows to list the Resources of the program before and after compression by UPX.  Present both lists; compare and analyze.
5. Try compile+build+run of the Go source code on Linux x8664, and then with UPX compression.
6. Try compile+build+run of the Go source code on Linux ARM64. (Compression by UPX is not yet supported.)

**Comment by anacrolix** [comment] 2024-08-13 01:18
> @anacrolix The setup seems to be not simple. The debugging strategy is to remove complication.
> 
> 1. Please confirm the development path:  Go-language source code ==> Go-compiled and built for WIndows 11 x86_64 ==> compressed by UPX ==> run on Windows 11 ARM64 ==> complaint by Go runtime.

Yes

> 2. Does the compressed-by-UPX code run without complaint on Windows 11 x86_64? If so, then the machinery which emulates Windows 11 x86_64 on Windows 11 ARM64 becomes a prime suspect, although the Go runtime support could contribute.

Yes

> 3. When the Go source is compiled and built directly for, and run on, Windows 11 ARM64, then does the Go runtime complain?  If so, then the problem lies in the Go source, or the Go compile-and-build machinery, or the Go runtime.  (Compression by UPX is not a problem source.)

I have not tried this. I'm not sure I have the set up available to me but yes that makes sense.

> 4. Use general low-level debugging tools for WIndows to list the Resources of the program before and after compression by UPX.  Present both lists; compare and analyze. 

I don't have the knowledge for this. The binary can be generated and upx'd easily enough with the repro I provided. One of the links above contains a prebuilt binary for testing to get started.

> 5. Try compile+build+run of the Go source code on Linux x8664, and then with UPX compression.
> 6. Try compile+build+run of the Go source code on Linux ARM64. (Compression by UPX is not yet supported.)

These make sense after the above points.

Point 3 definitely makes the most sense to try next.

**Comment by anacrolix** [comment] 2024-11-19 04:23
Let me know if any more information is required. I've provided all the necessary reproduction material

**Comment by jreiser** [comment] 2024-11-22 02:52
This problem is not a bug in UPX.  It is a bug in the Microsoft emulation on ARM64  of Windows apps built for x86_64.  Here is the evidence, run under Windows 10 Home, version 22H2 (x86_64), OS build 19045.5131:
```
D:\issue839>dir

 Directory of D:\issue839

11/21/2024  01:24 PM    <DIR>          .
11/21/2024  01:24 PM    <DIR>          ..
11/21/2024  01:24 PM         4,764,672 go-issue-68268.exe
11/21/2024  01:24 PM         2,743,296 go-issue-68268-packed.exe
               2 File(s)      7,507,968 bytes

D:\issue839>.\go-issue-68268.exe
main returning

D:\issue839>.\go-issue-68268-packed.exe
main returning

D:\issue839>
```
which shows that both the original go-issue-68268.exe and the packed file produced by upx-4.2.4 [the current release of UPX] execute successfully on x86_64, producing the same one-line message `main returning`.

So: either the Microsoft implementation on ARM64 of the Windows API has a "native" bug, or the emulator of x86_64 apps does not translate the code written for Windows API on x86_64 correctly onto ARM64, or the emulator is not "bug-for-bug compatible" with the implementation of Windows API on x86_64.  [If there is any ambiguity in the Windows API, then a faithful emulator must make the same choices.]  You should file a bug report against the Microsoft emulator.

Closing as "Not a bug" in UPX.

**Closed as completed by jreiser** 2024-11-22 02:52 UTC
Labels: os:Windows, notabug

**Comment by anacrolix** [comment] 2024-11-22 08:45
Thanks for looking into it. I've used upx as a convenience so the workaround for me is just to not just use upx. I'll try to submit it upstream somewhere, and I'll link here when I do for others to follow.

**Comment by anacrolix** [comment] 2024-11-26 03:08
I tried to submit it upstream but Microsoft/Windows seemingly have no developer friendly way to do this.
