### ISSUE TITLE
UPX 3.96 crashes on running graal linux native image 

### ISSUE THREAD

**Issue by bajajyog** [upx/upx#405] opened 2020-08-31 06:34 UTC
## What's the problem (or question)?
Used UPX 3.96 linux/amd64 to compress the graal vm native image. After running the compressed native image file, it is crashing.

## What should have happened?
normal native image without compression run fine.

## Do you have an idea for a solution?
no

## How can we reproduce the issue?
I can share the sample program. this works fine on mac os. only on linux this does not work

## Please tell us details about your environment.
upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Linux AMD64

**Comment by jreiser** [comment] 2020-08-31 13:21
Please upload ("Attach files by ...") or provide a URL to the actual executable which fails. Compress the upload using gzip, zip, or ..tgz to save space on github.

**Comment by bajajyog** [comment] 2020-08-31 15:21
[graal-native-image-hello-world.zip](https://github.com/upx/upx/files/5151137/graal-native-image-hello-world.zip)

**Comment by bajajyog** [comment] 2020-08-31 15:24
Attached the zip file. I am running graal  vm native image on amazon linux 2 docker.  I used UPX 3.96 linux/amd64. 

Let me know if you need any more or I need to diff UPX target architecture.

**Comment by bajajyog** [comment] 2020-08-31 15:24
You can run the native image as .graal-native-image-hello-world

**Comment by bajajyog** [comment] 2020-09-02 18:06
I tried with past diff versions of UPX Releases. Still no success.

**Comment by bajajyog** [comment] 2020-09-02 23:43
This is the error coming on executing native image

Fatal error: Failed to create a new Isolate. (code 7)

**Comment by bajajyog** [comment] 2020-09-03 18:12
Let me know if you need any more info from my side for this issue. Appreciate if we can get some updates for this issue on Linux AMD64.  I want to deploy native image at AWS Lambda. Native image size is 337 MB. AWS lambda allows max 250 MB.
UPX is the only last hope to deploy the native image to AWS lambda.

**Comment by jreiser** [comment] 2020-09-04 17:28
64-bit ET_EXEC had a bug; fixed in commit noted above on `devel` branch.
UPX compression of the graal executable saves only 5.7MB:
```
        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   8832536 ->   3118824   35.31%   linux/amd64   graal            
```
so if you must reduce from 337MB to 250MB then you need other reductions, too.

**Comment by bajajyog** [comment] 2020-09-04 18:46
I need some help how to build the code from source or if you can build the UPX linux/amd64 from dev and give the upx executable.
Following steps done
export UPX_UCLDIR=/Users/bajajy/Downloads/upx-3.96/src/ucl-1.03
downloaded LZMA SDK and added into upx src
downlaod ucl 1.03 and added into upx src.   --- advise how to build ucl
run "make all" -- getting linker error
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [upx.out] Error 1

**Comment by bajajyog** [comment] 2020-09-04 18:46
Thanks for doing fix quickly in UPX for this.

**Comment by jreiser** [comment] 2020-09-04 20:20
@bajajyog Well, what is the complaint when changing the Makefile for ucl-1.03 to include the `-v` parameter, by adding it to the CFLAGS and CXXFLAGS variables?  For example:
```
CFLAGS = -g -O2 -v
CXXFLAGS = -g -O2 -v
```
For pre-built binaries, then consult each of these links in sequence.  At each step choosing the next link that you want:
```
https://github.com/upx/upx-automatic-builds
https://github.com/upx/upx-automatic-builds/tree/devel-20200904-0a27bff-travis
https://github.com/upx/upx-automatic-builds/tree/devel-20200904-0a27bff-travis/amd64-linux-gcc-7-release
https://github.com/upx/upx-automatic-builds/blob/devel-20200904-0a27bff-travis/amd64-linux-gcc-7-release/upx-git-0a27bff51730.out
```
and then click on the Download button on that last page (or some other page depending on which compiler you like, etc.)

**Comment by bajajyog** [comment] 2020-09-04 20:55
Thanks for pre build binaries info

**Comment by bajajyog** [comment] 2020-09-05 01:21
I took the amd64/linux out executable from below path. Still same issue. On running native image, I am still getting the same error.


https://github.com/upx/upx-automatic-builds/blob/devel-20200904-0a27bff-travis/amd64-linux-gcc-7-release/upx-git-0a27bff51730.out

**Comment by jreiser** [comment] 2020-09-05 02:17
Works for me, after pressing the Download button on the page linked in the above comment https://github.com/upx/upx/issues/405#issuecomment-687507938 :
```
$ ls -l upx-git-0a27bff51730.out
-rwxrwxr-x. 1 user group 4204169 Sep  4 19:10 upx-git-0a27bff51730.out
$ sha256sum upx-git-0a27bff51730.out
3d50caf131df865e130ee038f7f4a6af2e875c9b1e62aa59343c164471a57d90  upx-git-0a27bff51730.out
$ chmod +x upx-git-0a27bff51730.out   # make it executable
$ ./upx-git-0a27bff51730.out -f -o foo graal   # compress
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2020
UPX git-0a27bf  Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020

        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   8832536 ->   3118824   35.31%   linux/amd64   foo                           

Packed 1 file.

WARNING: this is an unstable beta version - use for testing only! Really.
$ ./foo   # run the compressed version, getting the expected output
Fatal error: Failed to create a new Isolate. (code 7)
```

**Comment by bajajyog** [comment] 2020-09-05 15:51
On running native image ./foo, this error is coming "Fatal error: Failed to create a new Isolate. (code 7)". If it works fine, native image should print hello world. Thanks for your message.

**Comment by jreiser** [comment] 2020-09-05 20:24
The graal program attempts network connections which affect its output but are not documented in the recipe to reproduce the problem.  Please document.  For instance, `strace ./graal-native-image-hello-world` shows
```
14371 socket(AF_INET6, SOCK_STREAM, IPPROTO_IP) = 4
14371 getsockname(0, 0x7ffe60878730, [28]) = -1 ENOTSOCK (Socket operation on non-socket)
14371 openat(AT_FDCWD, "/proc/net/if_inet6", O_RDONLY) = 5
14371 fstat(5, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
14371 read(5, "00000000000000000000000000000001"..., 1024) = 108
14371 close(5)                          = 0
14371 close(4)                          = 0
14371 socket(AF_INET, SOCK_STREAM, IPPROTO_IP) = 4
14371 setsockopt(4, SOL_SOCKET, SO_REUSEPORT, [1], 4) = 0
14371 close(4)                          = 0
14371 openat(AT_FDCWD, "/proc/net/ipv6_route", O_RDONLY) = 4
14371 fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
14371 read(4, "00000000000000000000000000000001"..., 1024) = 1024
14371 read(4, "0000000 00200200       lo\n", 1024) = 26
14371 read(4, "", 1024)                 = 0
14371 close(4)                          = 0
14371 openat(AT_FDCWD, "/proc/net/if_inet6", O_RDONLY) = 4
14371 fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
14371 read(4, "00000000000000000000000000000001"..., 1024) = 108
14371 close(4)                          = 0
14371 openat(AT_FDCWD, "/proc/net/if_inet6", O_RDONLY) = 4
14371 fstat(4, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
14371 read(4, "00000000000000000000000000000001"..., 1024) = 108
14371 read(4, "", 1024)                 = 0
14371 close(4)                          = 0
```
which are attempts to initiate communication via IPv6.  One common output when such attempts fail is
```
$ ./graal-native-image-hello-world
omsai
omsai0
omsai1
omsai2
omsai3
omsai4
omsai5
omsai6
omsai7
omsai8
omsai9
$ 
```

**Comment by jreiser** [comment] 2020-09-05 20:59
The graal program makes bad assumptions about the layout of the address space at run time.  For instance, graal assumes that the first line of /proc/self/maps contains the name of the main program; but this is not necessarily true.  The evidence which strongly suggests this bad assumption by graal is given by `strace`:
```
openat(AT_FDCWD, "/proc/self/maps", O_RDONLY) = 3
read(3, "00400000-00c09000 r-xp 00000000 "..., 4096) = 3883
close(3)                          = 0
openat(AT_FDCWD, "/path/to/github-issue405/graal", O_RDONLY) = 3
```
When the compressed-by-UPX program runs, then the corresponding output is
```
openat(AT_FDCWD, "/proc/self/maps", O_RDONLY) = 3
read(3, "00400000-00c09000 r-xp 00000000 "..., 4096) = 3935
close(3)                                = 0
openat(AT_FDCWD, "", O_RDONLY)          = -1 ENOENT (No such file or directory)
```
which illustrates the empty pathname for address 0x400000.

The operating system is allowed to map other files at lower addresses than the main program, and those addresses will appear before the main program in /proc/self/maps.  Also, in the case of a compressed ET_EXEC program such as graal-native-image-hello-world,  then the de-compressed program must occupy the same pages as the uncompressed program would, so the mapping of those pages cannot be from the compressed file.

In general, /proc/self/exe need not exist at all, and in fact stops existing when all of those pages become unmapped.  UPX used to unmap everything, but now preserves the original /proc/self/exe by mapping its first page into a page near the high end of the stack.  UPX also adds one environment variable whose name is "\x20\x20\x20" (three spaces) and whose value is the the original result of `readlink("/proc/self/exe",,)`.  This concession by UPX enables `readlink("/proc/self/exe",,)` to continue to work.

On Linux the safest way to retrieve the pathname that was specified to execve() is via
```
#include <elf.h>
    char const *name = (char const *)getauxval(AT_EXECFN);
```

By planting a breakpoint just before the UPX run-time stub transfers control to the de-compressed program, I have examined the layout of memory and the values of the stack, enviornment, and Auxiliary vector produced by UPX; and I believe that all is correct.
```
(gdb) x/i $pc
0x00007ffff7fcc110 in ?? ()
=> 0x7ffff7fcc110:  mov    %rsp,%rdi
(gdb) shell cat /proc/13399/maps
00400000-00c09000 r-xp 00000000 00:00 0 
00c09000-00e08000 ---p 00000000 00:00 0 
00e08000-00e0a000 rw-p 00000000 00:00 0 
7ffff7fca000-7ffff7fcb000 r--p 00000000 08:26 45772667                   /path/to/github-issue405/foo
7ffff7fcb000-7ffff7fcc000 r--p 00000000 08:03 1836176                    /usr/lib64/ld-2.29.so
7ffff7fcc000-7ffff7fec000 r-xp 00001000 08:03 1836176                    /usr/lib64/ld-2.29.so
7ffff7fec000-7ffff7ff4000 r--p 00021000 08:03 1836176                    /usr/lib64/ld-2.29.so
7ffff7ff4000-7ffff7ff5000 ---p 00000000 00:00 0 
7ffff7ff5000-7ffff7ff7000 rw-p 00029000 08:03 1836176                    /usr/lib64/ld-2.29.so
7ffff7ff7000-7ffff7ff8000 rw-p 00000000 00:00 0 
7ffff7ff9000-7ffff7ffd000 r--p 00000000 00:00 0                          [vvar]
7ffff7ffd000-7ffff7fff000 r-xp 00000000 00:00 0                          [vdso]
7ffffffdd000-7ffffffff000 rw-p 00000000 00:00 0                          [stack]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
(gdb) x/32xg $sp   # argc, argv, env
0x7fffffffd610: 0x0000000000000001  0x00007fffffffd9d0
0x7fffffffd620: 0x0000000000000000  0x00007fffffffd981
0x7fffffffd630: 0x00007fffffffd9fb  0x00007fffffffda0b
0x7fffffffd640: 0x00007fffffffda59  0x00007fffffffda69
   [[snip]]
0x7fffffffd810: 0x00007fffffffe85c  0x00007fffffffeae1
0x7fffffffd820: 0x00007fffffffeb12  0x00007fffffffeb89
0x7fffffffd830: 0x0000000000000000  0x0000000000000021
0x7fffffffd840: 0x00007ffff7ffd000  0x0000000000000010
(gdb) x/32xg  0x7fffffffd838   # auxv
0x7fffffffd838: 0x0000000000000021  0x00007ffff7ffd000
0x7fffffffd848: 0x0000000000000010  0x00000000b7ebfbff
0x7fffffffd858: 0x0000000000000006  0x0000000000001000
0x7fffffffd868: 0x0000000000000011  0x0000000000000064
0x7fffffffd878: 0x0000000000000003  0x0000000000400040
0x7fffffffd888: 0x0000000000000004  0x0000000000000038
0x7fffffffd898: 0x0000000000000005  0x0000000000000008
0x7fffffffd8a8: 0x0000000000000007  0x00007ffff7fcb000
0x7fffffffd8b8: 0x0000000000000008  0x0000000000000000
0x7fffffffd8c8: 0x0000000000000009  0x00000000004041f4
0x7fffffffd8d8: 0x000000000000000b  0x00000000000003e8
0x7fffffffd8e8: 0x000000000000000c  0x00000000000003e8
0x7fffffffd8f8: 0x000000000000000d  0x00000000000003e8
0x7fffffffd908: 0x000000000000000e  0x00000000000003e8
0x7fffffffd918: 0x0000000000000017  0x0000000000000000
0x7fffffffd928: 0x0000000000000019  0x00007fffffffd9b9
(gdb)
0x7fffffffd938: 0x000000000000001a  0x0000000000000000
0x7fffffffd948: 0x000000000000001f  0x00007fffffffefcd
0x7fffffffd958: 0x000000000000000f  0x00007fffffffd9c9
0x7fffffffd968: 0x0000000000000000
```

**Comment by bajajyog** [comment] 2020-09-06 03:45
Thanks for your analysis of this issue.  On MAC, I compressed the native image by UPX and it runs fine. only on linux, this issue is happening. Please advise, any fix can be made in UPX or we need to reach  Oracle Graal VM team for fixes in their code base. Once agin, thanks for UPX analysis.

**Comment by jreiser** [comment] 2020-09-06 13:46
Relying on the first line of /proc/self/maps to contain the name of the executable file, is definitely a bug.  Instead use code like this:
```
#include <elf.h>
#include <sys/auxv.h>
#include <stdio.h>

int main(int argc, char *argv[])
{
    printf("auxval(AT_EXECFN)=%s\n", getauxval(AT_EXECFN));
    return 0;
}
```
The AT_EXECFN member of Elf64_auxv_t[] is somewhat new; I formalized it in Linux kernel twelve years ago on  2008-07-21.  If you want something that is less Linux-specific, then use `readlink("/proc/self/exe", buf, buflen)` but remember to add the trailing '\0'.
Even the filename does not give much information about the address space.  The only guarantee is that the PT_LOAD "segments" are present in the address space.  There is no Elf64_Shdr[] section table, and no debugging info (line numbers, etc.) unless those are contained within some PT_LOAD.  There also is no symbol table except the DT_SYMTAB (etc) entries of the PT_DYNAMIC segment; and only if PT_DYNAMIC is contained within some PT_LOAD.  Really the only thing useful about the filename is the directory name, and of course that might be a relative (non-absolute) pathname.  At least the `bash` shell sets the environment variable PWD as an absolute path.

Obviously I cannot guarantee the absence of other problems, but this definitely is the first one.

**Comment by jreiser** [comment] 2020-09-06 19:57
Based on code comments in graal source about /proc/self/maps in files graal/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/ProcFSSupport.java and graal/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxImageHeapProvider.java; and about /proc/self/exe in files graal/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxProcessPropertiesSupport.java and graal/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/linux/LinuxImageHeapProvider.java, then it seems that graal really wants to find a file that corresponds to many of the mapped pages for the current process; but there is no such file for an address space that is generated by the upx run-time de-compressor.  In theory it is somewhat strange that this should be a fatal problem, because the address space generated by the upx de-compressor is just a bunch of .bss pages whose bytes happen not to be all-zero, and graal certainly must handle .bss pages that have been dirtied by the _init(), DT_INIT, and DT_INITARRAY intialization subroutines for shared libraries.

If the run-time environment allows for generating files that can be executed, then one work-around is to apply `upx -d -o name` to the compressed file, then execute the de-compressed file `name`; but `upx` is not a small program.  For i386, then upx compression accepts the command-line option `--force-execve` which specializes the `-d` de-compression down to a couple kilobytes and embeds it into the output as the de-compressor; but this mode is for i386 only.

If graal really needs a file but cannot find one when upx de-compression has been used, then perhaps graal should create and write such a file, using the information from /proc/self/maps.

**Comment by bajajyog** [comment] 2020-09-07 04:06
The way UPX has dev releases builds. oracle graal vm team also provides dev builds. I took the latest Graal CE dev build for linux amd64. UPX is working fine there.  Does Graal team fixed this issue, i do not know. but UPX is working for me in Linux AMD 64 with latest graal VM CE dev build. Thanks for your all the help. It reduced the size from 337 MB to 79 MB. UPX is working fine in AWS lambda also.

**Comment by peter-hofer** [comment] 2020-09-07 13:56
I've been working on the relevant parts of the GraalVM Native Image code. What you are observing is our mechanism for spawning _isolates_, which are multiple independent execution contexts in a process. Each of these isolates has its own copy of an _image heap_, which is a set of objects that exists at the beginning of an isolate's execution. In order to create an isolate, we locate the file from where we have been loaded into memory (mapped into the process), either an executable or a shared library, and create a new mapping of the image heap from there. Since there is no direct mapping with UPX, it is incompatible with our approach. However, we have recently introduced a fallback mechanism that simply resorts to copying the existing pristine image heap in memory for the new isolate, which is potentially slower and uses more memory because it prevents sharing of unmodified pages, but it should always work. This would be why it's working with a recent GraalVM build. So I think this issue and https://github.com/oracle/graal/issues/2830 can be considered solved.

PS: we don't use `/proc/self/exe` or `getauxval(AT_EXECFN)` because we need to support shared library builds and it also doesn't work in some other cases, like when running under Valgrind. Also, our code doesn't assume `/proc/self/maps` contains our mapping in the first line, we scan it until we find an entry containing a specific page from our image file.

**Closed** 2020-09-13 20:27 UTC
