### ISSUE TITLE
upx-3.96-mipsel_linux can not work

### ISSUE THREAD

**Issue by binave** [upx/upx#504] opened 2021-05-22 06:28 UTC
run ./upx --version it's stuck,
upx-3.95-mipsel_linux is work

**Comment by jreiser** [comment] 2021-05-22 13:31
Confirmed: there is something wrong with upx-3.96-mipsel_linux:
```
$ curl --location https://github.com/upx/upx/releases/download/v3.96/upx-3.96-mipsel_linux.tar.xz | xzcat - | tar xvf -
upx-3.96-mipsel_linux/
upx-3.96-mipsel_linux/BUGS
upx-3.96-mipsel_linux/COPYING
upx-3.96-mipsel_linux/LICENSE
upx-3.96-mipsel_linux/NEWS
upx-3.96-mipsel_linux/README
upx-3.96-mipsel_linux/README.1ST
upx-3.96-mipsel_linux/THANKS
upx-3.96-mipsel_linux/upx
upx-3.96-mipsel_linux/upx.1
upx-3.96-mipsel_linux/upx.doc
upx-3.96-mipsel_linux/upx.html
$ qemu-mipsel upx-3.96-mipsel_linux/upx --version   # running on x86_64
upx-3.96-mipsel_linux/upx: Invalid argument

$ sha256sum upx-3.96-mipsel_linux/upx
11e04f74f41ad6a32ded7b697a455765a9d4cbc0a06fac399e4a824dd3bc60f4  upx-3.96-mipsel_linux/upx
$ ls -l upx-3.96-mipsel_linux/upx
-rwxr-xr-x. 1 user group 449100 Jan 23  2020 upx-3.96-mipsel_linux/upx
$ readelf --headers upx-3.96-mipsel_linux/upx
ELF Header:
  Magic:   7f 45 4c 46 01 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF32
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           MIPS R3000
  Version:                           0x1
  Entry point address:               0x46a838
  Start of program headers:          52 (bytes into file)
  Start of section headers:          0 (bytes into file)
  Flags:                             0x1007, noreorder, pic, cpic, o32, mips1
  Size of this header:               52 (bytes)
  Size of program headers:           32 (bytes)
  Number of program headers:         2
  Size of section headers:           40 (bytes)
  Number of section headers:         0
  Section header string table index: 0

There are no sections in this file.

Program Headers:
  Type           Offset   VirtAddr   PhysAddr   FileSiz MemSiz  Flg Align
  LOAD           0x000000 0x00400000 0x00400000 0x6bc82 0x6bc82 R E 0x10000
  LOAD           0x000000 0x00470000 0x00470000 0x00000 0x1d0550 RW  0x10000
```

**Comment by jreiser** [comment] 2021-05-22 13:53
But the de-compressed verison is OK;
```
$ upx.out -d -f -o upx.unc upx-3.96-mipsel_linux/upx
$ qemu-mipsel upx.unc --version
upx 3.96
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43
Copyright (C) 1996-2020 Markus Franz Xaver Johannes Oberhumer
Copyright (C) 1996-2020 Laszlo Molnar
Copyright (C) 2000-2020 John F. Reiser
Copyright (C) 2002-2020 Jens Medoch
Copyright (C) 1995-2005 Jean-loup Gailly and Mark Adler
Copyright (C) 1999-2006 Igor Pavlov
UPX comes with ABSOLUTELY NO WARRANTY; for details type 'foo -L'.
```
So I'll investigate.

**Comment by jreiser** [comment] 2021-05-22 21:15
qemu-mips: According to https://bugs.launchpad.net/qemu-linaro/+bug/802228 from about ten years ago, the qemu-mipsel complaint `Invalid argument` on x86_64 relates to a problem with emulating a 32-bit architecture using a 64-bit architecture.  Supposedly fixed, but the launchpad page hints at problems propagating the patch.  So with regard to this current Issue with upx, then the complaint by qemu probably is not relevant.

upx for mipsel:   Debugging on mips hardware (big endian) shows an infinite loop in the decompression stub at `mprotect`.  The generated instructions do not save and restore the return address register around a  call to a support subroutine.  The effect is as if the change in stub/src/include/linux.h:
```
@@ -501,7 +498,7 @@ static int mprotect(void const *addr, size_t len, int prot)
         "bal sysgo"
     : "+r"(v0)
     : "r"(a0), "r"(a1), "r"(a2)
-    : "a3"
+    : "a3", "ra"
     );
     return v0;
 }
```
was not included in upx-3.96.  That's from `git diff d53376d672eacad70eb311f11654bfaa8686c6af cd58a66fda7323e45788c57d19d54bbec1b06377` where the second commit was on Mon May 25 14:13:01 2020 -0700.

@markus-oberhumer could there have been a hiccup in cross-compiling the stub code for mips and mipsel?  Directly invoking bin-upx-20210104/mipsel-linux-gcc-4.1.1 generates correct code to save and restore register `ra` around the `bal sysgo`.

**Comment by binave** [comment] 2021-05-23 15:59
````sh
curl --location https://github.com/upx/upx/releases/download/v3.96/upx-3.96-mipsel_linux.tar.xz | tar xJf -

shamus upx-3.96-mipsel_linux/upx
131a05f42a4d9ec9cd2d6ac79ed51bb3e84e1df8  upx-3.96-mipsel_linux/upx
root@EdgeRouter-X-5-Port:/home/ubnt# sha1sum upx 
131a05f42a4d9ec9cd2d6ac79ed51bb3e84e1df8  upx
root@EdgeRouter-X-5-Port:/home/ubnt# ./upx -v

### old:
root@EdgeRouter-X-5-Port:/home/ubnt# /config/upx -v
                       Ultimate Packer for eXecutables
                          Copyright (C) 1996 - 2018
UPX 3.95        Markus Oberhumer, Laszlo Molnar & John Reiser   Aug 26th 2018

Usage: upx [-123456789dlthVL] [-qvfk] [-o file] file..


````

**Comment by markus-oberhumer** [comment] 2022-08-17 19:58
Is this fixed in current git?

**Comment by jreiser** [comment] 2022-09-28 02:37
As discussed about 1.5 years ago on May 22, 2021 in https://github.com/upx/upx/issues/504#issuecomment-846464493, I believe that the infinite loop is due to a build error for mipsel.r3000-linux.elf-main.o.  The subroutine for `mprotect `in include/linux.h did not have the return address register `ra` included in the list of clobbered registers:
```
-    : "a3"
+    : "a3", "ra"
```
The result was that one of the instances of `mprotect` did not save and restore the outer return address, despite calling `sysgo` which overwrites register `ra`.  This would cause the `jr ra` to be a one-instruction infinite loop:
```
00000030 <mprotect>:  ## src/stub/tmp/mipsel.r3000-linux.elf-main.o.disasm
  30:   27bdfff8    addiu   sp,sp,-8
  34:   afbf0000    sw  ra,0(sp)   ## suspected as missing
  38:   0411fff8    bal 1c <sysgo>
  3c:   2402101d    li  v0,4125
  40:   8fbf0000    lw  ra,0(sp)   ## suspected as missing
  44:   00000000    nop
  48:   03e00008    jr  ra
  4c:   27bd0008    addiu   sp,sp,8
```
This suspicion can be verified with access to real hardware.  First, run `strace upx-3.96 --help` and note the system call output which stops at the infinite loop after:
```
62601 readlink("/proc/self/exe",0x407ff170,4095) = 44
62601 cacheflush(1082125744,244,3,1073291537,0,0) = 0
62601 mmap(0x00400000,2363392,PROT_NONE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0) = 0x00400000
62601 mmap(0x00400000,2241104,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|MAP_FIXED,-1,0) = 0x00400000
62601 cacheflush(4194304,244,3,1073291537,0,0) = 0
62601 cacheflush(4194548,2240860,3,1073717395,0,0) = 0
62601 mprotect(0x00400000,2241104,PROT_EXEC|PROT_READ) = 0
```
Then run `upx-3.96 --help` under gdb, sending SIGINT (Ctrl-C) after a couple seconds, and examining the instruction stream with `(gdb) x/10i $pc-8*4`.

My real mipsel-r3000 is inaccessible in storage, so I cannot verify those executions personally.  Also, `strace` and `gdb` cannot be run on the same process at the same time.

I have inspected src/stub/src/include/linux.h, src/stub/Makefile and src/stub/tmp/mipsel.r3000-linux.elf-main.d, and they are correct in `devel` branch.  A re-build can verify proper operation using `qemu-mipsel --strace ./upx-N.NN-mipsel_linux --help`.

Closing this Issue.

**Closed by jreiser** 2022-09-28 02:37 UTC

**Comment by jreiser** [comment] 2022-09-28 08:54
Here is proof of the problem.  Using two processes:
```
qemu-mipsel --strace --singlestep -g 1234 upx-3.96-mipsel_linux/upx  &
mips-linux-gnu-gdb upx-3.96-mipsel_linux/upx
(gdb) target remote :1234
(gdb) stepi  # etc
```
and referring to the source files  mipsel.r3000-linux.elf-entry.S and mipsel.r3000-linux.elf-fold.S and i386-linux.elf-main.c in src/stub/src, I was able to single-step to the `mprotect` that is called from do_xmap().  The mprotect code is:
```
   0x3fffd7e8:	bal	0x3fffd7c4  ## call sysgo; set ra = 0x3fffd7f0
   0x3fffd7ec:	li	v0,4125   ## __NR_mprotect [in branch delay slot of 'bal']
   0x3fffd7f0:	jr	ra  ## infinite loop here because `bal` clobbers outer return address that was in `ra`
```
which does not save and restore the calling `ra`.
