### ISSUE TITLE
Compressing dynamic linker causes segfault

### ISSUE THREAD

**Issue by liamwhite** [upx/upx#121] opened 2017-09-13 01:50 UTC
## What's the problem (or question)?
After compressing the musl dynamic linker with upx, dynamic executables fail to load and segfault on launch.
```
root:alpine# chroot . /bin/sh
/ # exit

root:alpine# upx -qq lib/ld-musl-x86_64.so.1 
    563688 ->    410808   72.88%   linux/amd64   ld-musl-x86_64.so.1

root:alpine# chroot . /bin/sh
Segmentation fault

root:alpine# upx -qq -d lib/ld-musl-x86_64.so.1 
    563688 <-    410808   72.88%   linux/amd64   ld-musl-x86_64.so.1

root:alpine# chroot . /bin/sh
/ # exit
```

## What should have happened?
1. UPX should not compress the dynamic linker if it is incapable of doing so
2. If UPX can compress the dynamic linker, it should not segfault when invoked

## How can we reproduce the issue?

1. Download alpine [mini_root](http://dl-cdn.alpinelinux.org/alpine/v3.6/releases/x86_64/alpine-minirootfs-3.6.2-x86_64.tar.gz)
2. Extract alpine-minirootfs-3.6.2-x86_64.tar.gz to /tmp/alpine (root required to mknod ./alpine/dev/null)
3. `cd /tmp; sudo chroot alpine /bin/sh` demonstrates that the shell works
4. `sudo $(which upx) alpine/lib/ld-musl-x86_64.so.1`
5. `sudo chroot alpine /bin/sh` causes a segmentation fault
6. `sudo $(which upx) -d alpine/lib/ld-musl-x86_64.so.1` fixes the segfault

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.94
* Host Operating System and version: Linux 4.12
* Host CPU architecture: x86_64
* Target Operating System and version: Linux 4.12
* Target CPU architecture: x86_64

**Comment by jreiser** [comment] 2017-09-13 20:21
The problem is: when ld-musl (/lib/ld-musl-x86_64.so.1) is used as PT_INTERP for /bin/sh [as shown by "readelf --segments /bin/sh"], then ld-musl must be marked as DT_1_PIE in order for UPX to know that ld-musl is effectively a main program.  (The linux kernel starts a PT_INTERP at its .e_entry, as if it was a standalone main program without a PT_INTERP.  A shared library is first run at its DT_INIT by the PT_INTERP.  The difference requires different processing by UPX.)  Running "readelf --dynamic ld-musl-x86_64.so.1" shows that there is no DF_1_PIE flag: only the NOW flag (DF_1_NOW) is in the DT_FLAGS_1 word.  If you re-build ld-musl with -fPIE then it still will work as a PT_INTERP after being compressed by UPX.

**Comment by liamwhite** [comment] 2017-09-13 22:53
> The linux kernel starts a PT_INTERP at its .e_entry, as if it was a standalone main program without a PT_INTERP. A shared library is first run at its DT_INIT by the PT_INTERP. The difference requires different processing by UPX.

Is there significant effort involved in modifying the loader stub to handle both without requiring that a dynamic linker be DF_1_PIE?

**Comment by jreiser** [comment] 2017-09-14 00:17
Well, yes, the effort is significant. It's assembly language, and must be verified by single stepping the whole thing.
Marking with DF_1_PIE and compressing as a main program instead of as a shared library also saves around 49KB because more can be compressed.  You can compress stuff that the shared library linker might relocate, or the information that the shared library linker might need in order to relocate other modules.
Besides, there is a 2-minute workaround.  Use a hex editor to OR-in the DF_1_PIE bit into the DT_FLAGS_1 word of the PT_DYNAMIC segment.  DT_FLAGS_1 is 0x6ffffffb, the current value is DF_1_NOW (== 1) and DF_1_PIE is 0x08000000.  So find the tag 0x6ffffffb and change the following 64-bit value to 0x08000001.  The correct result is verified as:
```
$ readelf --dynamic ld-musl-x86_64.so.1

Dynamic section at offset 0x88d90 contains 16 entries:
  Tag        Type                         Name/Value
 0x000000000000000e (SONAME)             Library soname: [libc.musl-x86_64.so.1]
 0x000000000000000c (INIT)               0x1d7b6
 0x000000000000000d (FINI)               0x1e146
 0x0000000000000004 (HASH)               0x190
 0x000000006ffffef5 (GNU_HASH)           0x2f70
 0x0000000000000005 (STRTAB)             0x117c0
 0x0000000000000006 (SYMTAB)             0x6558
 0x000000000000000a (STRSZ)              17634 (bytes)
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000007 (RELA)               0x15ca8
 0x0000000000000008 (RELASZ)             2160 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x0000000000000018 (BIND_NOW)           
 0x000000006ffffffb (FLAGS_1)            Flags: NOW PIE
 0x000000006ffffff9 (RELACOUNT)          55
 0x0000000000000000 (NULL)               0x0
```
I did that, applied UPX, and the  compressed ld-musl works for me.

**Comment by jreiser** [comment] 2017-09-19 03:11
I am delaying the Close of this Issue because I have discovered another conflict between an "ordinary" executable and an executable used as a PT_INTERP.  De-compressing an ordinary executable requires updating the Elf_auxv[] (the values stored at the AT_* indices, such as at AT_PHDR) from the values that reflect the compressed a.out, to the values that reflect the un-compressed a.out.  De-compressing a PT_INTERP must not modify the Elf_auxv[] vector, and the operating system does not provide an efficient clue about whether the current execution is within the PT_INTERP.  Therefore, it is looking like UPX must see the command-line flag **-is-ptinterp** when compressing something that is to be used as a PT_INTERP.  Stay tuned.

**Comment by jreiser** [comment] 2017-10-18 20:18
This now works on amd64, IF: the executable is marked as <tt>DF_1_PIE</tt>, and if the flag <tt>--is_ptinterp</tt> is specified when compressing.  <tt>DF_1_PIE</tt> is required in order not to be a shared library, and <tt>--is_ptinterp</tt> is required in order to suppress modifications of the Elf64_auxv during de-compression of the PT_INTERP.

**Closed by jreiser** 2017-10-18 20:18 UTC
