### ISSUE TITLE
MSYS2: basename is already defined (with a fix)

### ISSUE THREAD

**Issue by f4grx** [upx/upx#257] opened 2019-03-04 09:58 UTC
## What's the problem (or question)?
upx does not build in msys2

```
g++ '-DUPX_VERSION_GITREV="8aadbcd786ab"' -O2 -fno-delete-null-pointer-checks -fno-strict-aliasing -fwrapv -funsigned-char -Wall -W -Wcast-align -Wcast-qual -Wmissing-declarations -Wpointer-arith -Wshadow -Wvla -Wwrite-strings -Werror -o c_file.o -c c_file.cpp
In file included from c_file.cpp:29:0:
conf.h:234:0: error: "basename" redefined [-Werror]
 #define basename            upx_basename

In file included from miniacc.h:4820:0,
                 from conf.h:86,
                 from c_file.cpp:29:
/usr/include/string.h:171:0: note: this is the location of the previous definition
 # define basename basename

cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:92: c_file.o] Error 1
```
## What should have happened?
upx should build without error

## Do you have an idea for a solution?
Apply this patch made with git diff:
```
diff --git a/src/conf.h b/src/conf.h
index 01eeb58d..8b0ac33d 100644
--- a/src/conf.h
+++ b/src/conf.h
@@ -231,6 +231,9 @@ typedef size_t upx_rsize_t;

 // avoid warnings about shadowing global functions
 #undef index
+#if defined(__MSYS2__)
+#undef basename
+#endif
 #define basename            upx_basename
 #define index               upx_index
 #define outp                upx_outp

```

Please note: I have added this define for safety, but it may not be required at all.

## How can we reproduce the issue?

1. install msys
2. clone devel branch
3. make all
4. previous error shows up

## Please tell us details about your environment.
upx git branch devel commit 8aadbcd786abd50b94f89c58d0be6674c033041d
UCL data compression library 1.03
zlib data compression library 1.2.11
LZMA SDK version 4.43

* Host Operating System and version: MSYS2 in win10
* Host CPU architecture: x86_64
* Target Operating System and version: various android
* Target CPU architecture: x86, x86_64, armeabi-v7a, arm64-v8a

Thank you

**Comment by jreiser** [comment] 2019-03-04 14:56
MSYS2 is broken.  FIx MSYS2; do not inflict its brokenness on apps.

`/usr/include/string.h:171:0: note: this is the location of the previous definition`
A "standard" #include file should not pollute the namespace by usurping the symbol `basename`.  In package glibc-headers-2.27-37.fc28 the declaration is guarded by `#ifdef  __USE_GNU`; MSYS2 should have a similar guard.  Why does MSYS2 modify what glibc provides?

Why should UPX pay attention to MSYS2?

**Comment by f4grx** [comment] 2019-03-04 15:02
No worries, you know better than me.

I will try to contact MSYS2, thanks for your time.

**Comment by f4grx** [comment] 2019-03-06 10:38
As expected this issue is starting a war in MSYS: they state it's not their problem.

https://github.com/msys2/MINGW-packages/issues/5020#issuecomment-469914155

I notice you also undefine the index function before redefining it. Would that be *that* impossible to implement this slight additional workaround?

Whatever you decide, I dont care. I have an easy local workaround.

I will continue to push this issue to cygwin.

**Comment by mati865** [comment] 2019-03-06 14:06
AFAIK Cygwin never haven't ever been using GitHub for their development, instructions on bug reposting are available here: https://cygwin.com/problems.html

**Comment by stahta01** [comment] 2019-03-30 10:16
Why are you trying to build upx under MSys2?
Just install it?

pacman -S upx

Tim S.

**Comment by f4grx** [comment] 2019-03-30 10:19
Because I am not dumb and I have reasons, like, needing to use the development branch because the msys package does not have features that I need? :) - and to be clear, it will never, because we need experimental changes to the source.

**Comment by stahta01** [comment] 2019-03-30 10:32
Then, you need to be smart if you are not dumb!
Why are you not using the MSys2 package as a starting point to build you custom version!
Why did you not state which of the three prompt you are building from?

Tim S.

**Comment by stahta01** [comment] 2019-03-30 10:43
Did you even look at the package?
[https://github.com/msys2/MSYS2-packages/blob/master/upx/basename.patch](https://github.com/msys2/MSYS2-packages/blob/master/upx/basename.patch)

**Comment by stahta01** [comment] 2019-03-30 11:36
The "How can we reproduce the issue" is missing many things.
What packages are needed to be installed?
What prompt is being used? (MSys2, MinGW 32, or MinGW 64)
Till I get those there is no way worth my time to try to duplicate the issue.

But, I am starting to believe the problem is the OP lack of knowledge; FLOSS projects do not accept minor un-needed code changes. The MSys2 team already patches the package for its internal building and the UPX team sees no reason to add to their maintained code. The problem appears to be the OP does not wish to do their own code maintenance and is trying to get others to do it. It a shame a Ham radio person is this unknowing.

Tim S.

**Comment by stahta01** [comment] 2019-03-30 11:45
The OP also did not give the details of the "clone devel branch" step.

Tim S.

**Comment by stahta01** [comment] 2019-03-30 12:04
The problem can not be duplicated when using MSys2's MinGW64 prompt.
I had at least these packages installed.
base-devel
mingw-w64-x86_64-gcc
git
mingw-w64-x86_64-ucl

The problem is caused by the OP not using the correct MSys2 MinGW prompt or by the OP refusing to apply patch needed when building on MSys2 non MinGW prompt.

Did not try to build on MSys2 non MinGW prompt since; that makes very little sense to do without using an MSys2 package.

Tim S.

**Comment by f4grx** [comment] 2019-03-30 19:58
Seriously, you comments are an offense.

I dont even want to participare in this conversation anymore.

I have a one liner to solve this problem, so closing it.

**Comment by bitraid** [comment] 2019-03-30 21:06
@f4grx UPX compiles successfully with MSYS2 under the MINGW prompt, which is what you should use when building native Windows applications. The MSYS prompt (where you get this error) should only be used when building for the MSYS2 environment.

**Comment by stahta01** [comment] 2019-03-31 16:22
@f4grx  Please close this issue; you will have a easier time when you learn how to use the tools.

NOTE: On github.com it is normal for the user to close the issue when he/she thinks it needs to be closed!

Tim S.

**Closed** 2019-03-31 17:29 UTC
