### ISSUE TITLE
UPX 3.93 does not build on Fedora 25

### ISSUE THREAD

**Issue by armijnhemel** [upx/upx#89] opened 2017-04-14 21:30 UTC
## What's the problem (or question)?

When I try to build UPX 3.93 on Fedora 25 the build fails:

g++ -O2 -fno-delete-null-pointer-checks -fno-strict-aliasing -fwrapv -funsigned-char -Wall -W -Wcast-align -Wcast-qual -Wmissing-declarations -Wpointer-arith -Wshadow -Wvla -Wwrite-strings -Werror -o upx.out c_file.o c_init.o c_none.o c_screen.o compress.o compress_lzma.o compress_ucl.o compress_zlib.o except.o file.o filter.o filteri.o help.o lefile.o linker.o main.o mem.o msg.o p_armpe.o p_com.o p_djgpp2.o p_exe.o p_lx_elf.o p_lx_exc.o p_lx_interp.o p_lx_sh.o p_mach.o p_ps1.o p_sys.o p_tmt.o p_tos.o p_unix.o p_vmlinx.o p_vmlinz.o p_w32pe.o p_w64pep.o p_wcle.o packer.o packer_c.o packer_f.o packhead.o packmast.o pefile.o s_djgpp2.o s_object.o s_vcsa.o s_win32.o snprintf.o stdcxx.o ui.o util.o work.o -lucl -lz
./../src/stub/scripts/check_whitespace.sh ./..
ERROR: binary file detected ./src/c_file.o:

and the build stops.

## What should have happened?

The build should have finished :-)

## Do you have an idea for a solution?

I have no idea, but it was mentioned in issue 49 as well in one of the comments (compilation on Ubuntu failed)

## How can we reproduce the issue?

1. install Fedora 25
2. install ucl-devel
3. grab v3.93 tarballs for upx and upx-lzma-sdk
4. unpack lzma-sdk in correct location
5. set UPX_UCLDIR according to documentation
6. make all

## Please tell us details about your environment.

* UPX version used (`upx --version`): 3.93
* Operating System and version: Linux, Fedora 25, full updated
* CPU architecture: x86_64

**Comment by markus-oberhumer** [comment] 2017-04-18 10:38
Duplicate of #64.

**Closed by markus-oberhumer** 2017-04-18 10:38 UTC
