### ISSUE TITLE
UPX 4.2.0 can't start in XP SP3 x86 and XP SP2 x64.

### ISSUE THREAD

**Issue by Uber-1** [upx/upx#731] opened 2023-10-30 15:24 UTC
Both win32 and win64 binaries v.4.2.0 can't start in XP (but 32 and 64 bit).  No error messages there. Just can't launch.
DOS v4.2.0 version WORKS in XP 32 bit.
Both win32 and win64 binaries v.4.1.0 WORK in XP (but 32 and 64 bit). 
Both win32 and win64 binaries v.4.2.0 WORK in my Win10 21H2.

**Comment by peter8777555** [comment] 2023-10-30 16:46
Fixed in V4.2.1

**Comment by markus-oberhumer** [comment] 2023-10-30 17:32
Thanks, this is already getting addressed.

Duplicate of #726

**Closed as completed** 2023-11-01 12:19 UTC
Labels: duplicate

**Comment by Uber-1** [comment] 2023-11-01 17:28
Confirm fixed in 4.2.1, Thanks.
