### ISSUE TITLE
UPX unpacked exe crashing

### ISSUE THREAD

**Issue by Vityacv** [upx/upx#34] opened 2016-12-12 20:18 UTC
## What's the problem (or question)?

Double defined dll in import table causes crash on unpacked exe

## What should have happened?

Unpacked exe should run without crash

## How can we reproduce the issue?

1. Pack attached exe [test32.zip](https://github.com/upx/upx/files/647055/test32.zip) or build another from source located here http://www.manhunter.ru/assembler/382_fasm_i_upx_sozdani_drug_dlya_druga.html
2. Unpack it
3. Try to run and get crash

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 3.92-git-1c01b77a7196
* Operating System and version: archlinux amd64, windows 10
* CPU architecture: amd64

**Comment by AraHaan** [comment] 2016-12-14 08:28
What version of Visual Studio did you use? Because compressing anything using C++ 11 or newer has this issue for most Compressors.

**Comment by ml1050** [comment] 2016-12-25 16:34
AraHaan,

this is a different problem. Your problem is probably caused by the TLS callback bug, which is fixed on the devel branch. This problem is related to the import table handling, I'm working on it.

**Comment by ml1050** [comment] 2016-12-30 20:39
Fixed in c7cb0365364bd968f878d1b55aa59e453335d310.
Thanks for your report.

**Closed by ml1050** 2016-12-30 20:39 UTC
