### ISSUE TITLE
arm64-linux: 4.0.2 and newer crash on Oracle Cloud VM

### ISSUE THREAD

**Issue by theotherp** [upx/upx#737] opened 2023-11-20 20:47 UTC
## What's the problem (or question)?
From 4.0.2 onward I'm getting a `Segmentation fault` error when running upx. 4.0.1 is the last working version. I'm running on a VM on Oracle Cloud.

## What should have happened?
Newer versions should run.

## Do you have an idea for a solution?
Sorry, nope :-(
I tried getting some more information using gdb and google but I have no idea what I'm doing.

## How can we reproduce the issue?
Download 4.0.2 or newer and run on an Oracle Cloud VM? They're free.

## Please tell us details about your environment.
* UPX version used: 4.0.2, 4.2.0, 4.2.1
I'm pasting information from `hostnamectl`, hope that helps.
* Virtualization: kvm
* Operating System: Oracle Linux Server 8.6
* CPE OS Name: cpe:/o:oracle:linux:8:6:server
* Kernel: Linux 5.4.17-2136.314.6.2.el8uek.aarch64
* Architecture: arm64

**Comment by jreiser** [comment] 2023-11-22 01:48
@theotherp Please post specific directions on how to create and access an Oracle Cloud VM that matches your environment.  Finding the right documentation, making the right choices during configuration, etc., is info that will speed investigation.  Plus, when I tried to install an Oracle VM on a local x86_64 some months ago, then I discovered network changes that interfered with existing apps and operations.  I have also had trouble installing VMware VMs on a local x86_64.  So VMs are on my list of "beware" apps.

**Comment by theotherp** [comment] 2023-11-23 16:14
@jreiser I could mail you credentials for SSH access so you can test it yourself.

**Comment by jreiser** [comment] 2023-11-23 17:37
@theotherp My email address is contained in the "Author:" line for any commit that I make to the UPX source; so `git log  |  grep 'Author:.*jreiser'  |  sed 1q` .

Here is how to get some diagnostic info that is helpful:
```
$ ./upx-4.0.2 --version   # attempt to run a failing version
       (shell says something about Segmentation fault)
$ echo $?   # the exit status of the last command: sometimes the shell is not too specific
$ dmesg  |  tail -30   # recent whole-system messages: look for AVC denials by SELinux

$ strace ./upx-4.0.2 --version   # show system calls: what does UPX do, how far does it get?

$ gdb ./upx-4.0.2     # use debugger
(gdb) run --version     # invoke ./upx-4.0.2 with argument
     SIGSEGV
(gdb) bt     # get a backtrace of subroutine calls
(gdb) info reg     # display all CPU registers
(gdb) x/i $pc    # instruction at point of error
(gdb) x/11i $pc-5*4   # instruction stream surrounding the point of error
(gdb) x/16xw $sp     # dump the top of stack
```

**Comment by theotherp** [comment] 2023-11-23 18:00
The commands don't work because of the segmentation fault error.

```
[build@hydrabuild upx-4.2.1-arm64_linux]$ ls
COPYING  NEWS    THANKS.txt  upx.1         upx-doc.txt
LICENSE  README  upx         upx-doc.html
[build@hydrabuild upx-4.2.1-arm64_linux]$ ./upx --version
Segmentation fault
[build@hydrabuild upx-4.2.1-arm64_linux]$ gdb upx
GNU gdb (GDB) Red Hat Enterprise Linux 8.2-19.0.1.el8
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from upx...(no debugging symbols found)...done.
(gdb) run --version
Starting program: /tmp/upx-4.2.1-arm64_linux/upx --version
During startup program terminated with signal SIGSEGV, Segmentation fault.
(gdb)
(gdb) bt
No stack.
(gdb) info reg
The program has no registers now.
(gdb) x/i $pc
No registers.
```

I'll send instructions via mail.

**Comment by jreiser** [comment] 2023-11-23 22:32
@markus-oberhumer The immediate cause is page alignment is not 64K:
```
$ readelf --segments /bin/date   # on Oracle 5.4.17-2136.314.6.2.el8uek.aarch64
Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
 LOAD           0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000015e18 0x0000000000015e18  R E    0x10000   # 64K
  LOAD           0x000000000001ef90 0x000000000002ef90 0x000000000002ef90
                 0x0000000000001158 0x00000000000012b0  RW     0x10000


$ readelf --segments upx-4.2.1-arm64_linux/upx   # as distributed
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x0000000000001000 0x000000000020dff0  RW     0x2000    #  8K
  LOAD           0x0000000000000000 0x000000000060e000 0x000000000060e000
                 0x000000000008d26c 0x000000000008d26c  R E    0x2000
```
So the issue is, how and why was 8K chosen for the build of upx?  UPX tends to set the alignment of the output to be the alignment of the input.   It should be easy for the CI build process to choose 64K; but then page fragments in the file can be quite large, and compression ratio can deteriorate noticeably, especially for non-large .text.

Stack at invocation:
```
(gdb) x/8xg $sp
0xfffffffff310:	0x0000000000000001	0x0000fffffffff5ac   # argc, beginning of argv[]
0xfffffffff320:	0x0000000000000000	0x0000fffffffff5ba   # beginning of environment
0xfffffffff330:	0x0000fffffffffcb8	0x0000fffffffffce8
0xfffffffff340:	0x0000fffffffffcf7	0x0000fffffffffd08
(gdb) 
0xfffffffff350:	0x0000fffffffffd1f	0x0000fffffffffd33
0xfffffffff360:	0x0000fffffffffd41	0x0000fffffffffd5a
0xfffffffff370:	0x0000fffffffffd6d	0x0000fffffffffd76
0xfffffffff380:	0x0000fffffffffd8e	0x0000fffffffffd9c
(gdb) 
0xfffffffff390:	0x0000fffffffffda5	0x0000fffffffffdb4
0xfffffffff3a0:	0x0000fffffffffdd6	0x0000fffffffffdef
0xfffffffff3b0:	0x0000fffffffffe02	0x0000fffffffffe0d
0xfffffffff3c0:	0x0000fffffffffe26	0x0000fffffffffe36
(gdb) 
0xfffffffff3d0:	0x0000fffffffffe4a	0x0000fffffffffe65
0xfffffffff3e0:	0x0000fffffffffe6d	0x0000fffffffffe79
0xfffffffff3f0:	0x0000fffffffffeaf	0x0000fffffffffece
0xfffffffff400:	0x0000ffffffffff28	0x0000ffffffffff36
(gdb) 
0xfffffffff410:	0x0000ffffffffff59	0x0000000000000000
0xfffffffff420:	0x0000000000000021	0x0000fffff7fa0000   # beginning of auxv; /usr/include/elf.h Elf64_auxv_t[]
0xfffffffff430:	0x0000000000000033	0x0000000000001270
0xfffffffff440:	0x0000000000000010	0x0000000010119fff
(gdb) 
0xfffffffff450:	0x0000000000000006	0x0000000000010000   # AT_PAGESZ(6)  is 64K
0xfffffffff460:	0x0000000000000011	0x0000000000000064
0xfffffffff470:	0x0000000000000003	0x0000aaaaaaaa0040
0xfffffffff480:	0x0000000000000004	0x0000000000000038
(gdb) 
0xfffffffff490:	0x0000000000000005	0x0000000000000009
0xfffffffff4a0:	0x0000000000000007	0x0000fffff7fb0000
0xfffffffff4b0:	0x0000000000000008	0x0000000000000000
0xfffffffff4c0:	0x0000000000000009	0x0000aaaaaaaa3558
(gdb) 
0xfffffffff4d0:	0x000000000000000b	0x00000000000003ea
0xfffffffff4e0:	0x000000000000000c	0x00000000000003ea
0xfffffffff4f0:	0x000000000000000d	0x00000000000003ea
0xfffffffff500:	0x000000000000000e	0x00000000000003ea
(gdb) 
0xfffffffff510:	0x0000000000000017	0x0000000000000000
0xfffffffff520:	0x0000000000000019	0x0000fffffffff588
0xfffffffff530:	0x000000000000001a	0x0000000000000000
0xfffffffff540:	0x000000000000001f	0x0000ffffffffffea
(gdb) 
0xfffffffff550:	0x000000000000000f	0x0000fffffffff598
0xfffffffff560:	0x000000000000001b	0x0000000000000001
0xfffffffff570:	0x0000000000000000	0x0000000000000000   # end of auxv
```

**Comment by markus-oberhumer** [comment] 2023-11-24 00:08
The official Linux versions are built with upx-linux-musl-gcc-9.2.0-toolchains-20200226.tar.xz  from https://github.com/upx/upx-stubtools/releases/tag/v20160918

I think I have not changed this since v4.0.0, so why does v4.0.1 work and v4.0.2 doesn't ?

And do the **unpacked** official arm64 binaries work?

**Comment by jreiser** [comment] 2023-11-24 03:12
The unpacked official upx-4.2.1-arm64_linux/upx (unpacked by running on 5.10.0-11-arm64 #1 SMP Debian 5.10.92-1 (2022-01-18) aarch64 GNU/Linux with 4KB pages) runs correctly on Oracle 5.4.17-2136.314.6.2.el8uek.aarch64 with 64KB pages.  The address-space layout is:
```
$ readelf --segments upx.unc
Elf file type is EXEC (Executable file)
Entry point 0x40096c
There are 5 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000000400000 0x0000000000400000
                 0x00000000001f7bb0 0x00000000001f7bb0  R E    0x10000
  LOAD           0x00000000001f8570 0x0000000000608570 0x0000000000608570
                 0x0000000000001e40 0x0000000000005a80  RW     0x10000   # ends at (0x608570 + 0x5a80) = 0x60dff0
  TLS            0x00000000001f8570 0x0000000000608570 0x0000000000608570
                 0x0000000000000000 0x0000000000000010  R      0x8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RW     0x10
  GNU_RELRO      0x00000000001f8570 0x0000000000608570 0x0000000000608570
                 0x0000000000001a90 0x0000000000001a90  R      0x1   # ends at (0x608570 + 0x1a90) = 0x60a000
```
The relevant code in UPX is in function PackLinuxElf64::pack1 in file p_lx_elf.cpp:
```
        if (PT_GNU_RELRO64 == type) {
            // .p_align can be like 2M, which is a huge over-estimate.
            // RELRO ends on a page boundary: usually close to actual page_size
            unsigned offset = get_te64(&phdr->p_offset);
            unsigned filesz = get_te64(&phdr->p_filesz);
            if (!(0xfff & (filesz + offset))) { // a 4KiB boundary
                unsigned b = 12;
                while (!(~(~0u << b) & (filesz + offset))) {
                    ++b;
                }
                lg2_page = umin(lg2_page, -1+ b);
            } 
        }
```
The reason for the UPX code is disagreement over the use of large page sizes, such as 2MB and 1GB on x86_64 (and even larger on PowerPC64), instead of the very common 4KB on most machines, and 4K/16K/64K on arm64.  A large page size reduces TLB misses and some overhead in the operating system, but typically incurs a space penalty in the file system because of the alignment constraints that virtual addresses impose on file offsets.  In particular, a few years ago there was a rash of x86_64 apps with alignment of 2MB, which caused large "holes" of zero bytes between segments, and much "wasted" space in the filesystem.  This made UPX look bad because the compression tended to be overwhelmed by the alignment constraint.

In response, I observed that (p_vaddr + p_memsz) of GNU_RELRO ended on an address that ends with many zero bits.  If it is intended that the hardware+OS match that, then the actual page size must be a divisor.  In this case, 0x2000 is the largest power of 2 which divides 0x60a000.

Notice that there is a conflict between PT_LOAD[1] with (p_vaddr + p_memsz) of (0x608570 + 0x5a80)  having RW protection, and GNU_RELRO with (p_vaddr + p_memsz) of (0x608570 + 0x1a90) having R-only protection: GNU_RELRO starts at the same p_vaddr 0x608570 as PT_LOAD[1], and is a subset of PT_LOAD[1].  Both protections cannot apply to the same address range. So deducing that the software build tools intended that the page size actually is 0x2000, is a reasonable compromise.

Perhaps the UPX code should not attempt any changes as long as p_align <= 64KB.  Or is there another policy alternative?

**Comment by markus-oberhumer** [comment] 2023-11-24 11:56
Well, I'm clearly no expert about current ELF details, but maybe your heuristic can be adapted to consider the target architecture?

**Comment by jreiser** [comment] 2023-11-26 20:02
Fixed on branch `devel4` by commit da35fc8ff39372a28ac74f4c3d06582b450b5b5d which is included in commit beef022126ec93a2e74f26295708bb9aa09ad841 .  See the Actions for the `beef022` commit.

**Comment by theotherp** [comment] 2023-11-26 20:58
I don't understand a word but glad you got it fixed!

**Comment by jreiser** [comment] 2023-11-26 21:16
@theotherp On this current page, click the Actions item in the menu bar near the top.  On that page, click the title of the job [Honor .p_align <= 64K; else assume 4K is also available](https://github.com/upx/upx/actions/runs/6997813779), then on the destination page scroll down to the Artifacts to select the auto-build for the environment that you want.

**Closed as completed** 2023-11-29 17:43 UTC
Labels: os:Linux
