### ISSUE TITLE
Support LZ4 for faster decompression and executable startup

### ISSUE THREAD

**Issue by yehonatanz** [upx/upx#751] opened 2024-01-02 10:30 UTC
## What's the problem (or question)?
I ran upx on the nodejs binary (see more details in the reproduce section).
A quick check showed `upx` incurs a 300ms penalty to binary startup time.
I suspect most of this time is spent on decompression.

## What should have happened?
Binary should have started up faster.

## Do you have an idea for a solution?
Perhaps using `lz4` for compression will help? A quick benchmark on my machine shows it's fastest when decompressing a similarly sized executable (~70ms vs gzip's ~280ms)
I suggest a `upx --lz4` option (similar to the existing `--lzma` option) with a description stating `lz4` is faster for decompressing large binaries.
(Not married to `lz4`, any algorithm with faster decompression times will work)

Another idea: add an option to brute through many methods and settling for the one fastest to start up (or possibly best trade off).

## How can we reproduce the issue?
1. I tested inside `node:20-slim` container with `upx` `docker cp`'d in 
2. `time node -e 'console.log(1)` --> 60ms
3. `upx --best $(which node) -o /tmp/node.upx.best`
4. `time /tmp/node.upx.best -e 'console.log(1)'` --> 377ms
5. `upx -1 $(which node) -o /tmp/node.upx.1`
6. `time /tmp/node.upx.1 -e 'console.log(1)'` --> 349ms
Obviously that's not a thorough measurement, but IMHO it's significant enough.

## Please tell us details about your environment.

* UPX version used (`upx --version`): 4.43
* Host Operating System and version: Debian 12 bookworm (`node:20-slim` container on an intel mac)
* Host CPU architecture: amd64
* Target Operating System and version: Debian 12 bookworm (native)
* Target CPU architecture: amd64 (native)

**Comment by jreiser** [comment] 2024-01-02 14:47
Please attach or give the URL to an actual file which behaves as described.  Among other things, the file sizes are not given.  Also, the recipe gives no source for `node:20-slim` and `node`, and the behavior cannot be reproduced without that information.

**Comment by yehonatanz** [comment] 2024-01-02 15:43
@jreiser Whoops sorry, I thought specifying a docker image was plenty clear, guess I was too much in my own head 😅 

Get the executable using:
```bash
curl -s https://nodejs.org/dist/v20.10.0/node-v20.10.0-linux-x64.tar.xz | tar -Oxf - node-v20.10.0-linux-x64/bin/node > node
```
Uncompressed size: 92M (96227728 bytes)
The docker image I was referring to is `node:20.10.0-bookworm-slim` ([dockerhub](https://hub.docker.com/layers/library/node/20.10.0-bookworm-slim/images/sha256-df49e2dc50b7b1f91b44201432cefaf034f66e549bcbd3a29745ffff439afc9e?context=explore))

**Comment by markus-oberhumer** [comment] 2024-01-02 16:46
Please note that the UPX stub will decompress the **whole** program at startup while otherwise pages are mostly demand-loaded, so this startup-time benchmark is somewhat misleading.

And you might want to try a squashfs filesystem.

**Comment by jreiser** [comment] 2024-01-03 06:51
Discussion https://github.com/upx/upx/discussions/723 "Compression of large executables" has some intro about squashfs.

**Comment by markus-oberhumer** [comment] 2024-01-04 02:40
In any case I'm **very** hesitant to making any unnecessary stub changes at this point because of Security/AntiVirus software considerations, so this is WONTFIX for now.

**Closed as not planned by markus-oberhumer** 2024-01-04 02:40 UTC
Labels: enhancement, wontfix
