### ISSUE TITLE
Support .NET exe files

### ISSUE THREAD

**Issue by necros2k7** [upx/upx#340] opened 2020-01-31 11:16 UTC

**Comment by jreiser** [comment] 2020-01-31 14:31
The axiom of choice ("try to pack any .NET executable") does not apply.  You must upload ("Attach files by ...") an actual .NET executable.  (Small is preferable, of course.)  Compress the upload using zip, gzip, or .tgz so that Github can save space.

**Comment by necros2k7** [comment] 2020-02-01 02:23
[timertool.exe.gz](https://github.com/upx/upx/files/4142073/timertool.exe.gz)

**Comment by necros2k7** [comment] 2020-02-27 11:53
same issue https://github.com/upx/upx/issues/37

**Comment by markus-oberhumer** [comment] 2020-02-28 03:50
Duplicate of #37. Closing.

**Closed by markus-oberhumer** 2020-02-28 03:50 UTC
Labels: duplicate
