### ISSUE TITLE
 UPX unzip crash Bug!!!

### ISSUE THREAD

**Issue by x64bugreport** [upx/upx#444] opened 2020-12-29 06:33 UTC
The following example fails to run after unpack, it crashes directly!
UPX3.91/3.96 WIN7/WIN10 X64
use upx.exe -d besttrace.exe.besttrace will Crash!!!
[demo.zip](https://github.com/upx/upx/files/5749787/demo.zip)

**Comment by jreiser** [comment] 2020-12-29 07:17
The tip of `devel` branch works for me:
```
UPX git-da4f9f+ Markus Oberhumer, Laszlo Molnar & John Reiser   Jan 24th 2020
        File size         Ratio      Format      Name
   --------------------   ------   -----------   -----------
   3869360 <-   1576112   40.73%    win64/pe     foo

Unpacked 1 file.

```
Auto-builds of some recent commits to `devel` branch appear beneath https://github.com/upx/upx-automatic-builds .  AppVeyor CI has the builds for Windows.

**Comment by x64bugreport** [comment] 2020-12-29 08:58
@jreiser It is not that it cannot be unpacked, but it cannot run after unpacking, and the PE file is abnormal.

**Comment by bitraid** [comment] 2020-12-29 09:17
This is a duplicate of #75 (fixed on devel).

**Comment by x64bugreport** [comment] 2020-12-29 09:40
@bitraid 
Why does it still crash when using delevel upx unpack?

**Comment by bitraid** [comment] 2020-12-29 18:37
> @bitraid
> Why does it still crash when using delevel upx unpack?

That's because there is a bug (wrong endianness) in the latest available build, which is now fixed but there is no build available.
You can unpack the file using version 3.96 with: `upx -d --strip-relocs=0 demo.exe`.

**Comment by necros2k7** [comment] 2021-03-13 03:14
close issue

**Closed** 2021-03-13 18:28 UTC
