### ISSUE TITLE
UPX compressed x86_64 executable crashes on macOS Ventura 13.0

### ISSUE THREAD

**Issue by flyingbird** [upx/upx#613] opened 2022-10-26 11:31 UTC
Simple HelloWorld test source code.
int main(int argc, const char * argv[]) {
    printf("Hello, World!\n");
    return 0;
}

% file test 
test: Mach-O 64-bit executable x86_64

using "upx -1 test" to Packed the file.

run test, just crashed.
./test
zsh: segmentation fault  ./test

crash log:

Identifier:          test
Version:             ???
Code Type:           X86-64 (Native)
Role:                Unspecified
Parent Process:      zsh [800]
Coalition:           com.apple.Terminal [976]
Responsible Process: Terminal [798]

Date/Time:           2022-10-26 19:18:08.1390 +0800
Launch Time:         2022-10-26 19:18:08.1355 +0800
OS Version:          macOS 13.0 (22A380)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00007ff7b508fb34
Exception Codes: 0x0000000000000001, 0x00007ff7b508fb34
VM Region Info: 0x7ff7b508fb34 is not in any region.  Bytes after previous region: 31541  Bytes before following region: 1623340236
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      Stack                    7ff7b4888000-7ff7b5088000 [ 8192K] rw-/rwx SM=PRV  thread 0
--->  GAP OF 0x60c2b000 BYTES
      unused __TEXT            7ff815cb3000-7ff839ddb000 [577.2M] r-x/r-x SM=COW  ...ed lib __TEXT
Termination Reason: SIGNAL 11 Segmentation fault: 11

**Comment by markus-oberhumer** [comment] 2022-11-04 11:27
I fear we do not have enough info to support macOS 13 at this time - has Apple released any current kernel/libc/ld/... source code yet?

**Comment by flyingbird** [comment] 2022-11-04 12:38
Yes. Apple just release it.
https://github.com/apple-oss-distributions/xnu
It's macOS 13.

**Comment by markus-oberhumer** [comment] 2022-11-10 18:12
Duplicate of #612 .

**Closed** 2022-11-10 18:14 UTC
Labels: duplicate
