### ISSUE TITLE
Unpack failed with 'Exception: compressed data violation'

### ISSUE THREAD

**Issue by google-mirror** [upx/upx#599] opened 2022-09-20 11:05 UTC
This issue tracker is **ONLY** used for reporting bugs.
Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

## What's the problem (or question)?
Unpack failed with 'Exception: compressed data violation'

## What should have happened?
Unpack succeed

## Do you have an idea for a solution?
No

## How can we reproduce the issue?

1.upx -9 --android-shlib libwxhttpproxy.so
2.upx -d libwxhttpproxy.so

## Please tell us details about your environment.

* UPX version used (`upx --version`): upx 4.0.0-git-b4cb9f8b2f86
* https://github.com/upx/upx/actions/runs/3072317024
* https://github.com/upx/upx/suites/8337119777/artifacts/366741159

[libwxhttpproxy.zip](https://github.com/upx/upx/files/9606870/libwxhttpproxy.zip)

**Comment by markus-oberhumer** [comment] 2022-09-27 16:27
This also seems to affect 3.96

```
$ upx-3.96 --android-shlib libwxhttpproxy.so -o x1
$ upx-3.96 -t x1
testing x1 zsh: segmentation fault (core dumped)  upx-3.96 -t x1
```

**Comment by markus-oberhumer** [comment] 2022-10-07 13:37
The new bounds-checking improvements in the `devel4` branch nicely catch this, `lldb` says the problem is here:

```
frame #4: 0x00000000004973df upx`PackLinuxElf64::PackLinuxElf64help1(this=0x0000000000845a90, f=0x00007fffffffd3e0) at p_lx_elf.cpp:808:39
   805          f->seek(0, SEEK_SET);
   806          f->readx(file_image, file_size);
   807          phdri= (Elf64_Phdr *)(e_phoff + file_image);  // do not free() !!
-> 808          shdri= (Elf64_Shdr *)(e_shoff + file_image);  // do not free() !!
   809          if (opt->cmd != CMD_COMPRESS) {
   810              shdri = nullptr;
   811          }





```

**Comment by markus-oberhumer** [comment] 2022-10-25 07:11
@jreiser see https://github.com/upx/upx/blob/devel4/src/packer.h#L158 about canUnpack(); this is **not** a bool!

**Comment by markus-oberhumer** [comment] 2022-10-28 06:41
This is not a regression, so v4.0.1.

**Comment by jreiser** [comment] 2022-12-12 17:24
Compiler nits evaded in 4cdf77e16f7f3e4b94f8c1ae0c0941857a364078 .
Artifacts in https://github.com/upx/upx/actions/runs/3671179009 .
Please test.

**Comment by google-mirror** [comment] 2022-12-13 01:54
> Compiler nits evaded in [4cdf77e](https://github.com/upx/upx/commit/4cdf77e16f7f3e4b94f8c1ae0c0941857a364078) . Artifacts in https://github.com/upx/upx/actions/runs/3671179009 . Please test.

This fixs #599 (but not #629)

**Comment by jreiser** [comment] 2022-12-13 02:45
#629 is next.

**Comment by markus-oberhumer** [comment] 2022-12-22 20:54
This does not work for me with 4cdf77e16f7 (using the artifact link above) nor with current git HEAD, reopening.

```
$ ./upx --version-short
upx 4.0.2-git-4cdf77e16f7f

$ ./upx libwxhttpproxy.so -o x1
$ ./upx libwxhttpproxy.so -o x2 --android-shlib
$ md5sum libwxhttpproxy.so x1 x2
9462758c4d96803a4c2650bb8bc22207  libwxhttpproxy.so
92f152dbe78d8b9dda18d2ae8c449cfe  x1
f05a0b6be17c9f972a089c6889d3b1e3  x2

./upx -t x1 x2
testing x1
upx: x1: Exception: compressed data violation
testing x2
upx: x2: Exception: compressed data violation

Tested 2 files: 0 ok, 2 errors.
```

**Comment by jreiser** [comment] 2022-12-30 18:38
Fixed by above commit https://github.com/upx/upx/commit/98cb064538b30e4fdae6b92cc741a4d4d105100c .
Builds (artifacts) are available for a while at https://github.com/upx/upx/actions/runs/3808459232 .

**Closed by jreiser** 2022-12-30 18:38 UTC
Labels: os:Android
